"""AGENTS.md generator — deterministic, thin-by-default projection."""

from __future__ import annotations

from datetime import UTC, datetime

from rkp.core.models import Claim
from rkp.core.types import ClaimType, RiskClass, source_authority_precedence
from rkp.projection.adapters.base import AdapterResult
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import HostCapability

_RISK_ORDER: dict[RiskClass, int] = {
    RiskClass.SAFE_READONLY: 0,
    RiskClass.SAFE_MUTATING: 1,
    RiskClass.TEST_EXECUTION: 2,
    RiskClass.BUILD: 3,
    RiskClass.DESTRUCTIVE: 4,
}

_RISK_LABELS: dict[RiskClass, str] = {
    RiskClass.SAFE_READONLY: "Safe (read-only)",
    RiskClass.SAFE_MUTATING: "Safe (mutating)",
    RiskClass.TEST_EXECUTION: "Testing",
    RiskClass.BUILD: "Build",
    RiskClass.DESTRUCTIVE: "Destructive",
}


def _stable_sort_claims(claims: list[Claim]) -> list[Claim]:
    """Sort claims deterministically: authority ASC, scope ASC, type ASC, id ASC."""
    return sorted(
        claims,
        key=lambda c: (
            source_authority_precedence(c.source_authority),
            c.scope,
            c.claim_type.value,
            c.id,
        ),
    )


def _render_generation_header(
    *,
    repo: str,
    head: str,
    branch: str,
) -> str:
    """Render the generation header with provenance."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!-- Generated by RKP v0.1.0 | repo: {repo} | head: {head} "
        f"| branch: {branch} | timestamp: {ts} "
        "| DO NOT EDIT — corrections go through rkp review -->\n"
    )


def _render_commands_section(commands: list[Claim]) -> str:
    """Render the Commands section grouped by risk class."""
    if not commands:
        return ""

    by_risk: dict[RiskClass, list[Claim]] = {}
    for claim in commands:
        risk = claim.risk_class or RiskClass.BUILD
        by_risk.setdefault(risk, []).append(claim)

    lines: list[str] = ["## Commands\n"]
    for risk in sorted(by_risk, key=lambda r: _RISK_ORDER.get(r, 99)):
        label = _RISK_LABELS.get(risk, risk.value)
        lines.append(f"### {label}\n")
        lines.extend(f"- `{claim.content}`" for claim in by_risk[risk])
        lines.append("")

    return "\n".join(lines)


def _render_conventions_section(conventions: list[Claim]) -> str:
    """Render the Conventions section (empty in M2, populated in M3)."""
    if not conventions:
        return ""
    lines: list[str] = ["## Conventions\n"]
    lines.extend(f"- {claim.content}" for claim in conventions)
    lines.append("")
    return "\n".join(lines)


class AgentsMdAdapter:
    """Generates root AGENTS.md from claims."""

    def project(
        self,
        claims: list[Claim],
        capability: HostCapability,
        budget: BudgetTracker,
    ) -> AdapterResult:
        """Project claims into an AGENTS.md file.

        Budget enforcement: render the full body, check its size against
        the hard budget, and if over, iteratively remove lowest-priority
        claims until it fits.
        """
        sorted_claims = _stable_sort_claims(claims)

        command_claims = [c for c in sorted_claims if c.claim_type == ClaimType.VALIDATED_COMMAND]
        convention_claims = [c for c in sorted_claims if c.claim_type == ClaimType.ALWAYS_ON_RULE]

        all_claims = command_claims + convention_claims
        excluded: list[tuple[str, str]] = []

        # Provenance
        repo = ""
        head = ""
        branch = ""
        if sorted_claims:
            repo = sorted_claims[0].repo_id
            head = sorted_claims[0].provenance.repo_head
            branch = sorted_claims[0].branch

        header = _render_generation_header(repo=repo, head=head, branch=branch)
        hard_budget = capability.size_constraints.hard_budget_bytes

        # Start with all claims, remove from the end (lowest priority) until within budget
        included_commands = list(command_claims)
        included_conventions = list(convention_claims)

        while True:
            body = _render_commands_section(included_commands) + _render_conventions_section(
                included_conventions
            )
            full_content = header + "\n" + body
            content_bytes = len(full_content.encode("utf-8"))

            if content_bytes <= hard_budget:
                break

            # Remove the last (lowest priority) claim
            if included_conventions:
                removed = included_conventions.pop()
                excluded.append((removed.id, "exceeded hard budget"))
            elif included_commands:
                removed = included_commands.pop()
                excluded.append((removed.id, "exceeded hard budget"))
            else:
                break

        # Track included/omitted in budget for reporting
        for claim in included_commands + included_conventions:
            budget.try_include(claim, f"- `{claim.content}`\n")
        for claim_id, reason in excluded:
            # Find the claim for budget tracking
            matching = [c for c in all_claims if c.id == claim_id]
            if matching:
                budget.omitted.append((matching[0], reason))

        body = _render_commands_section(included_commands) + _render_conventions_section(
            included_conventions
        )
        full_content = header + "\n" + body

        return AdapterResult(
            files={"AGENTS.md": full_content},
            excluded_claims=excluded,
            overflow_report=budget.overflow_report,
        )
