"""CLAUDE.md generator — multi-file, thin-by-default projection for Claude Code."""

from __future__ import annotations

import json
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime

from rkp.core.models import Claim
from rkp.core.types import ClaimType, RiskClass, SourceAuthority, source_authority_precedence
from rkp.projection.adapters.base import AdapterResult
from rkp.projection.adapters.skills import SkillDescriptor, project_skills
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import HostCapability

_RISK_ORDER: dict[RiskClass, int] = {
    RiskClass.SAFE_READONLY: 0,
    RiskClass.SAFE_MUTATING: 1,
    RiskClass.TEST_EXECUTION: 2,
    RiskClass.BUILD: 3,
    RiskClass.DESTRUCTIVE: 4,
}

_RISK_LABELS: dict[RiskClass, str] = {
    RiskClass.SAFE_READONLY: "Safe (read-only)",
    RiskClass.SAFE_MUTATING: "Safe (mutating)",
    RiskClass.TEST_EXECUTION: "Testing",
    RiskClass.BUILD: "Build",
    RiskClass.DESTRUCTIVE: "Destructive",
}

# High-authority sources whose claims belong in always-on content.
_HIGH_AUTHORITY = frozenset(
    {
        SourceAuthority.HUMAN_OVERRIDE,
        SourceAuthority.DECLARED_REVIEWED,
        SourceAuthority.EXECUTABLE_CONFIG,
        SourceAuthority.CI_OBSERVED,
        SourceAuthority.INFERRED_HIGH,
    }
)


@dataclass(frozen=True)
class ProjectionDecision:
    """Why a claim ended up where it did."""

    claim_id: str
    destination: str  # "claude.md", "rules/<file>", "skills/<name>", "settings", "excluded"
    reason: str


def _stable_sort_claims(claims: list[Claim]) -> list[Claim]:
    """Sort claims deterministically: authority ASC, scope ASC, type ASC, id ASC."""
    return sorted(
        claims,
        key=lambda c: (
            source_authority_precedence(c.source_authority),
            c.scope,
            c.claim_type.value,
            c.id,
        ),
    )


def _render_generation_header(
    *,
    repo: str,
    head: str,
    branch: str,
) -> str:
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!-- Generated by RKP v0.1.0 | repo: {repo} | head: {head} "
        f"| branch: {branch} | timestamp: {ts} "
        "| DO NOT EDIT — corrections go through rkp review -->\n"
    )


def _render_commands_section(commands: list[Claim]) -> str:
    if not commands:
        return ""
    by_risk: dict[RiskClass, list[Claim]] = {}
    for claim in commands:
        risk = claim.risk_class or RiskClass.BUILD
        by_risk.setdefault(risk, []).append(claim)

    lines: list[str] = ["## Commands\n"]
    for risk in sorted(by_risk, key=lambda r: _RISK_ORDER.get(r, 99)):
        label = _RISK_LABELS.get(risk, risk.value)
        lines.append(f"### {label}\n")
        lines.extend(f"- `{claim.content}`" for claim in by_risk[risk])
        lines.append("")
    return "\n".join(lines)


def _render_conventions_section(conventions: list[Claim]) -> str:
    if not conventions:
        return ""
    lines: list[str] = ["## Conventions\n"]
    lines.extend(f"- {claim.content}" for claim in conventions)
    lines.append("")
    return "\n".join(lines)


def _render_guardrails_section(guardrails: list[Claim]) -> str:
    if not guardrails:
        return ""
    lines: list[str] = ["## Guardrails\n"]
    lines.extend(f"- {claim.content}" for claim in guardrails)
    lines.append("")
    return "\n".join(lines)


def _render_skills_reference(descriptors: list[SkillDescriptor]) -> str:
    if not descriptors:
        return ""
    lines: list[str] = ["## Skills\n"]
    lines.append("The following skills are available for detailed procedures:\n")
    lines.extend(
        f"- **{desc.name}**: {desc.description}"
        for desc in sorted(descriptors, key=lambda d: d.name)
    )
    lines.append("")
    return "\n".join(lines)


def _has_broad_applicability(claim: Claim) -> bool:
    """A claim has broad applicability if it targets 'all' or has no specific tags."""
    if not claim.applicability:
        return True
    return "all" in claim.applicability


def is_enforceable_restriction(claim: Claim) -> bool:
    """Check if a restriction is enforceable via settings.json deny rules.

    Public: shared by the Claude adapter and the get_guardrails MCP tool.
    """
    if claim.claim_type != ClaimType.PERMISSION_RESTRICTION:
        return False
    if claim.confidence < 0.95:
        return False
    # Only destructive command restrictions are enforceable
    content_lower = claim.content.lower()
    return "destructive" in content_lower or "require explicit confirmation" in content_lower


def _restriction_to_deny_pattern(claim: Claim) -> str | None:
    """Convert a restriction claim to a settings.json deny pattern.

    Uses glob: ``Bash({cmd}*)`` matches the command with or without additional args.
    """
    # Extract the command from "Command `xyz` is classified as destructive..."
    match = re.search(r"`([^`]+)`", claim.content)
    if match:
        cmd = match.group(1)
        return f"Bash({cmd}*)"
    return None


def _group_scoped_claims(claims: list[Claim]) -> dict[str, list[Claim]]:
    """Group scoped claims by overlapping paths for .claude/rules/ files."""
    groups: dict[str, list[Claim]] = defaultdict(list)
    for claim in claims:
        # Use the scope as the grouping key, normalized
        scope = claim.scope.strip("/")
        # Derive a file-name-friendly key from the scope
        key = re.sub(r"[^a-z0-9]+", "-", scope.lower()).strip("-")
        if not key:
            key = "general"
        groups[key].append(claim)
    return dict(groups)


class ClaudeMdAdapter:
    """Generates CLAUDE.md + .claude/rules/ + .claude/skills/ + settings snippet."""

    def project(
        self,
        claims: list[Claim],
        capability: HostCapability,
        budget: BudgetTracker,
    ) -> AdapterResult:
        """Project claims into Claude Code artifacts.

        Multi-file output:
        - CLAUDE.md (always-on, ~200 lines soft budget)
        - .claude/rules/*.md (path-scoped rules)
        - .claude/skills/*/SKILL.md (on-demand skills)
        - .claude/settings-snippet.json (enforceable permissions)
        """
        sorted_claims = _stable_sort_claims(claims)
        decisions: list[ProjectionDecision] = []
        files: dict[str, str] = {}

        # Provenance
        repo = sorted_claims[0].repo_id if sorted_claims else ""
        head = sorted_claims[0].provenance.repo_head if sorted_claims else ""
        branch = sorted_claims[0].branch if sorted_claims else ""
        header = _render_generation_header(repo=repo, head=head, branch=branch)

        # Categorize claims
        command_claims: list[Claim] = []
        convention_claims: list[Claim] = []
        guardrail_claims: list[Claim] = []
        scoped_claims: list[Claim] = []
        skill_candidates: list[Claim] = []

        for claim in sorted_claims:
            # Scoped claims go to .claude/rules/
            if claim.scope != "**" and claim.claim_type in (
                ClaimType.ALWAYS_ON_RULE,
                ClaimType.SCOPED_RULE,
                ClaimType.PERMISSION_RESTRICTION,
            ):
                scoped_claims.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination=f"rules/{claim.scope}",
                        reason="scoped claim routed to .claude/rules/",
                    )
                )
                continue

            # Narrow-applicability claims go to skills
            if claim.claim_type in (
                ClaimType.SKILL_PLAYBOOK,
                ClaimType.SCOPED_RULE,
            ) and not _has_broad_applicability(claim):
                skill_candidates.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="skills",
                        reason="narrow applicability routed to skill",
                    )
                )
                continue

            # Categorize by type for always-on content
            if claim.claim_type == ClaimType.VALIDATED_COMMAND:
                command_claims.append(claim)
            elif claim.claim_type in (ClaimType.ALWAYS_ON_RULE, ClaimType.SCOPED_RULE):
                if claim.source_authority in _HIGH_AUTHORITY:
                    convention_claims.append(claim)
                else:
                    skill_candidates.append(claim)
                    decisions.append(
                        ProjectionDecision(
                            claim_id=claim.id,
                            destination="skills",
                            reason="low-authority convention routed to skill",
                        )
                    )
                    continue
            elif claim.claim_type == ClaimType.PERMISSION_RESTRICTION:
                guardrail_claims.append(claim)
            elif claim.claim_type == ClaimType.SKILL_PLAYBOOK:
                skill_candidates.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="skills",
                        reason="skill-playbook claim routed to skill",
                    )
                )
                continue
            else:
                # Module boundaries, conflicts, prerequisites — not projected to CLAUDE.md
                continue

        # Budget overflow: fill CLAUDE.md up to soft budget, overflow to skills.
        # Use an incremental line counter (O(N)) instead of re-rendering (O(N^2)).
        always_on_commands: list[Claim] = []
        always_on_conventions: list[Claim] = []
        always_on_guardrails: list[Claim] = []

        soft_limit = capability.size_constraints.soft_budget_lines
        # Reserve lines for: header(1) + blank(1) + skills reference section
        # Estimate max 10 skills x 1 line each + 3 header lines = 13 lines reserved
        skills_reserve = 15
        # Section headers take ~3 lines each (## heading + blank + content start)
        line_count = header.count("\n") + 2
        sections_used: set[str] = set()

        def _try_add(
            claim: Claim,
            rendered: str,
            target_list: list[Claim],
            section_name: str,
            dest_reason: str,
        ) -> None:
            nonlocal line_count
            claim_lines = rendered.count("\n") + 1
            section_overhead = 3 if section_name not in sections_used else 0
            effective_limit = soft_limit - skills_reserve if soft_limit is not None else None
            if (
                effective_limit is not None
                and line_count + claim_lines + section_overhead > effective_limit
            ):
                skill_candidates.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="skills",
                        reason="budget overflow from CLAUDE.md",
                    )
                )
            else:
                target_list.append(claim)
                sections_used.add(section_name)
                line_count += claim_lines + section_overhead
                budget.try_include(claim, rendered)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="claude.md",
                        reason=dest_reason,
                    )
                )

        # Commands first
        for claim in command_claims:
            _try_add(
                claim,
                f"- `{claim.content}`\n",
                always_on_commands,
                "commands",
                "command included in always-on",
            )

        # Conventions next
        for claim in convention_claims:
            _try_add(
                claim,
                f"- {claim.content}\n",
                always_on_conventions,
                "conventions",
                "convention included in always-on",
            )

        # Guardrails
        for claim in guardrail_claims:
            _try_add(
                claim,
                f"- {claim.content}\n",
                always_on_guardrails,
                "guardrails",
                "guardrail included in always-on",
            )

        # Generate skills from overflow + narrow-applicability claims
        skill_files, skill_descriptors = project_skills(
            skill_candidates, path_prefix=".claude/skills"
        )
        files.update(skill_files)

        # Build CLAUDE.md
        body = (
            _render_commands_section(always_on_commands)
            + _render_conventions_section(always_on_conventions)
            + _render_guardrails_section(always_on_guardrails)
            + _render_skills_reference(skill_descriptors)
        )
        files["CLAUDE.md"] = header + "\n" + body

        # Build .claude/rules/ files
        if scoped_claims:
            scoped_groups = _group_scoped_claims(scoped_claims)
            for group_key, group_claims in sorted(scoped_groups.items()):
                sorted_group = _stable_sort_claims(group_claims)
                # Collect paths for frontmatter
                paths = sorted({c.scope for c in sorted_group})
                rule_lines: list[str] = [
                    "---",
                    f"description: Rules for {', '.join(paths)}",
                    "paths:",
                ]
                rule_lines.extend(f"  - {p}" for p in paths)
                rule_lines.append("---")
                rule_lines.append("")
                rule_lines.extend(f"- {claim.content}" for claim in sorted_group)
                rule_lines.append("")
                files[f".claude/rules/{group_key}.md"] = "\n".join(rule_lines)

        # Build settings snippet (enforceable permissions).
        # Check all guardrail claims (always-on + scoped) for enforceable restrictions.
        all_restriction_claims = guardrail_claims + [
            c for c in scoped_claims if c.claim_type == ClaimType.PERMISSION_RESTRICTION
        ]
        deny_patterns: list[str] = []
        for claim in all_restriction_claims:
            if is_enforceable_restriction(claim):
                pattern = _restriction_to_deny_pattern(claim)
                if pattern:
                    deny_patterns.append(pattern)

        if deny_patterns:
            settings_snippet = {
                "permissions": {
                    "deny": sorted(set(deny_patterns)),
                }
            }
            files[".claude/settings-snippet.json"] = json.dumps(settings_snippet, indent=2) + "\n"

        # Build excluded claims list and overflow report
        excluded: list[tuple[str, str]] = [
            (d.claim_id, d.reason) for d in decisions if d.destination not in ("claude.md",)
        ]

        # Add provenance to overflow report
        overflow = budget.overflow_report
        overflow["decisions"] = [
            {"claim_id": d.claim_id, "destination": d.destination, "reason": d.reason}
            for d in decisions
        ]

        return AdapterResult(
            files=files,
            excluded_claims=excluded,
            overflow_report=overflow,
        )
