"""Copilot adapter — multi-file projection for GitHub Copilot coding agent.

Produces up to 4 artifact types:
- .github/copilot-instructions.md (always-on, thin-by-default)
- .github/instructions/*.instructions.md (path-scoped with applyTo frontmatter)
- .github/workflows/copilot-setup-steps.yml (constraint-validated environment setup)
- Tool allowlist snippet (JSON, suggested MCP configuration)

Key design decisions:
- Copilot also reads AGENTS.md — copilot-instructions.md is intentionally thin
  to avoid duplicating content already in AGENTS.md.
- Setup-steps are constraint-validated BEFORE writing. Invalid setup-steps can
  break the Copilot coding agent for the entire repo.
- Tool allowlist is conservative: only read-only tools in the allow list.
- Copilot runs autonomously — guardrails are especially prominent.
"""

from __future__ import annotations

import json
import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime
from typing import Any, cast

import yaml

from rkp.core.models import Claim
from rkp.core.types import ClaimType, RiskClass, SourceAuthority, source_authority_precedence
from rkp.projection.adapters.base import AdapterResult
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import HostCapability

# High-authority sources whose claims belong in always-on content.
_HIGH_AUTHORITY = frozenset(
    {
        SourceAuthority.HUMAN_OVERRIDE,
        SourceAuthority.DECLARED_REVIEWED,
        SourceAuthority.EXECUTABLE_CONFIG,
        SourceAuthority.CI_OBSERVED,
        SourceAuthority.INFERRED_HIGH,
    }
)

# Supported keys at the job level in copilot-setup-steps.yml.
_SUPPORTED_JOB_KEYS = frozenset({"runs-on", "timeout-minutes", "steps", "env", "permissions"})

# Unsupported keys at the job level.
_UNSUPPORTED_JOB_KEYS = frozenset(
    {"services", "container", "strategy", "needs", "outputs", "if", "concurrency"}
)

# Maximum timeout in minutes.
_MAX_TIMEOUT_MINUTES = 59

# Default timeout.
_DEFAULT_TIMEOUT_MINUTES = 30

# Action mappings for runtime setup.
_RUNTIME_ACTIONS: dict[str, tuple[str, str, str]] = {
    "python": ("actions/setup-python@v5", "python-version", "Python"),
    "node": ("actions/setup-node@v4", "node-version", "Node.js"),
    "go": ("actions/setup-go@v5", "go-version", "Go"),
    "java": ("actions/setup-java@v4", "java-version", "Java"),
    "ruby": ("actions/setup-ruby@v1", "ruby-version", "Ruby"),
}

# The read-only MCP tools available for the tool allowlist.
_READONLY_TOOLS: tuple[str, ...] = (
    "get_conventions",
    "get_module_info",
    "get_prerequisites",
    "get_validated_commands",
    "get_repo_overview",
    "get_preflight_context",
    "get_guardrails",
    "get_conflicts",
    "get_claim",
    "get_instruction_preview",
)

# Tools that are NOT read-only.
_READWRITE_TOOLS: tuple[str, ...] = ("refresh_index",)


@dataclass(frozen=True)
class ProjectionDecision:
    """Why a claim ended up where it did."""

    claim_id: str
    destination: str
    reason: str


def _stable_sort_claims(claims: list[Claim]) -> list[Claim]:
    """Sort claims deterministically: authority ASC, scope ASC, type ASC, id ASC."""
    return sorted(
        claims,
        key=lambda c: (
            source_authority_precedence(c.source_authority),
            c.scope,
            c.claim_type.value,
            c.id,
        ),
    )


def _render_generation_header(
    *,
    repo: str,
    head: str,
    branch: str,
    file_desc: str = "",
) -> str:
    """Render the generation header with provenance."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    desc = f" ({file_desc})" if file_desc else ""
    return (
        f"<!-- Generated by RKP v0.1.0{desc} | repo: {repo} | head: {head} "
        f"| branch: {branch} | timestamp: {ts} "
        "| DO NOT EDIT — corrections go through rkp review -->\n"
    )


def _render_yaml_generation_header(
    *,
    repo: str,
    head: str,
    branch: str,
) -> str:
    """Render YAML comment header with provenance."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"# Generated by RKP — DO NOT EDIT. Corrections go through `rkp review`.\n"
        f"# Repo: {repo} | HEAD: {head} | Branch: {branch} | {ts}\n"
    )


def validate_setup_steps(content: dict[str, Any]) -> list[str]:
    """Validate copilot-setup-steps.yml against known constraints.

    Returns list of validation errors. Empty = valid.
    """
    errors: list[str] = []

    # Must have a 'jobs' key
    jobs_raw: object = content.get("jobs")
    if jobs_raw is None:
        errors.append("Missing 'jobs' key")
        return errors

    if not isinstance(jobs_raw, dict):
        errors.append("'jobs' must be a mapping")
        return errors

    jobs = cast(dict[str, Any], jobs_raw)

    # Exactly one job
    if len(jobs) != 1:
        errors.append(f"Must have exactly 1 job, found {len(jobs)}")
        return errors

    # Job must be named 'copilot-setup-steps'
    job_name: str = str(next(iter(jobs)))
    if job_name != "copilot-setup-steps":
        errors.append(f"Job must be named 'copilot-setup-steps', found '{job_name}'")

    job_raw: object = jobs[job_name]
    if not isinstance(job_raw, dict):
        errors.append(f"Job '{job_name}' must be a mapping")
        return errors

    job = cast(dict[str, Any], job_raw)

    # Timeout check
    timeout: object = job.get("timeout-minutes")
    if timeout is not None:
        try:
            timeout_val = int(str(timeout))
            if timeout_val > _MAX_TIMEOUT_MINUTES:
                errors.append(
                    f"timeout-minutes ({timeout_val}) exceeds maximum ({_MAX_TIMEOUT_MINUTES})"
                )
            if timeout_val <= 0:
                errors.append(f"timeout-minutes ({timeout_val}) must be positive")
        except (ValueError, TypeError):
            errors.append(f"timeout-minutes must be an integer, got '{timeout}'")

    # Unsupported keys
    job_keys: set[str] = {str(k) for k in job}
    unsupported = job_keys & _UNSUPPORTED_JOB_KEYS
    if unsupported:
        errors.append(f"Unsupported job keys: {', '.join(sorted(unsupported))}")

    # Check for unknown keys (not in supported or unsupported lists)
    unknown = job_keys - _SUPPORTED_JOB_KEYS - _UNSUPPORTED_JOB_KEYS
    if unknown:
        errors.append(f"Unknown job keys: {', '.join(sorted(unknown))}")

    # Steps validation
    steps_raw: object = job.get("steps")
    if steps_raw is not None:
        if not isinstance(steps_raw, list):
            errors.append("'steps' must be a list")
        else:
            steps_list = cast(list[Any], steps_raw)
            for i, step_raw in enumerate(steps_list):
                if not isinstance(step_raw, dict):
                    errors.append(f"Step {i} must be a mapping")
                    continue
                step = cast(dict[str, Any], step_raw)
                # Check for unpinned action versions
                uses: object = step.get("uses")
                if isinstance(uses, str) and "@" not in uses:
                    errors.append(
                        f"Step {i}: action '{uses}' should be pinned to a version (e.g., @v4)"
                    )

    return errors


def _extract_runtime_info(claims: list[Claim]) -> dict[str, str]:
    """Extract runtime information from environment prerequisite claims.

    Returns {runtime_name: version} for known runtimes.
    """
    runtimes: dict[str, str] = {}

    for claim in claims:
        if claim.claim_type != ClaimType.ENVIRONMENT_PREREQUISITE:
            continue
        content = claim.content
        # Match patterns like "Python 3.12", "Node.js 20", etc.
        for runtime_key, (_, _, label) in _RUNTIME_ACTIONS.items():
            if label.lower() in content.lower():
                # Extract version number
                match = re.search(rf"{re.escape(label)}\s+([0-9][0-9.]*)", content, re.IGNORECASE)
                if match:
                    runtimes[runtime_key] = match.group(1)
                elif runtime_key not in runtimes:
                    # Mark as present but version unknown
                    runtimes[runtime_key] = ""

    return runtimes


def _extract_setup_commands(claims: list[Claim]) -> list[str]:
    """Extract setup commands from validated command claims."""
    commands: list[str] = []
    for claim in claims:
        if claim.claim_type != ClaimType.VALIDATED_COMMAND:
            continue
        if "setup" in claim.applicability or "install" in claim.content.lower():
            commands.append(claim.content)
    return commands


def generate_setup_steps(
    claims: list[Claim],
    *,
    repo: str = "",
    head: str = "",
    branch: str = "",
) -> tuple[str, list[str]]:
    """Generate copilot-setup-steps.yml from claims.

    Returns (yaml_content, validation_errors).
    """
    runtimes = _extract_runtime_info(claims)
    setup_commands = _extract_setup_commands(claims)

    # Build steps
    steps: list[dict[str, Any]] = [{"uses": "actions/checkout@v4"}]

    for runtime_key in sorted(runtimes):
        if runtime_key in _RUNTIME_ACTIONS:
            action, version_key, _label = _RUNTIME_ACTIONS[runtime_key]
            step: dict[str, Any] = {"uses": action}
            version = runtimes[runtime_key]
            if version:
                step["with"] = {version_key: version}
            steps.append(step)

    # Add setup/install commands
    steps.extend({"name": "Install dependencies", "run": cmd} for cmd in setup_commands)

    # Build workflow structure
    workflow: dict[str, Any] = {
        "name": "Copilot Setup Steps",
        "on": "workflow_dispatch",
        "jobs": {
            "copilot-setup-steps": {
                "runs-on": "ubuntu-latest",
                "timeout-minutes": _DEFAULT_TIMEOUT_MINUTES,
                "steps": steps,
            }
        },
    }

    # Validate
    validation_errors = validate_setup_steps(workflow)

    # Render YAML
    header = _render_yaml_generation_header(repo=repo, head=head, branch=branch)
    yaml_body = yaml.dump(workflow, default_flow_style=False, sort_keys=False, allow_unicode=True)

    return header + "\n" + yaml_body, validation_errors


def generate_tool_allowlist() -> dict[str, Any]:
    """Generate the MCP tool allowlist for Copilot.

    Only read-only tools in the allow list. refresh_index explicitly denied.
    """
    return {
        "tools": {
            "repo-knowledge-plane": {
                "allow": list(_READONLY_TOOLS),
                "deny": list(_READWRITE_TOOLS),
            }
        }
    }


def is_copilot_enforceable(claim: Claim) -> bool:
    """Check if a restriction is enforceable via Copilot's tool allowlist."""
    if claim.claim_type != ClaimType.PERMISSION_RESTRICTION:
        return False
    if claim.confidence < 0.95:
        return False
    content_lower = claim.content.lower()
    return "destructive" in content_lower or "require explicit confirmation" in content_lower


class CopilotAdapter:
    """Generates Copilot artifacts from claims.

    Multi-file output:
    - .github/copilot-instructions.md (thin always-on)
    - .github/instructions/*.instructions.md (path-scoped)
    - .github/workflows/copilot-setup-steps.yml (validated)
    - .copilot-tool-allowlist.json (suggested config snippet)
    """

    def project(
        self,
        claims: list[Claim],
        capability: HostCapability,
        budget: BudgetTracker,
    ) -> AdapterResult:
        """Project claims into Copilot artifacts."""
        sorted_claims = _stable_sort_claims(claims)
        decisions: list[ProjectionDecision] = []
        files: dict[str, str] = {}

        # Provenance
        repo = sorted_claims[0].repo_id if sorted_claims else ""
        head = sorted_claims[0].provenance.repo_head if sorted_claims else ""
        branch_name = sorted_claims[0].branch if sorted_claims else ""

        # Categorize claims
        command_claims: list[Claim] = []
        convention_claims: list[Claim] = []
        guardrail_claims: list[Claim] = []
        scoped_claims: list[Claim] = []
        env_claims: list[Claim] = []

        for claim in sorted_claims:
            # Scoped claims go to .github/instructions/*.instructions.md
            if claim.scope != "**" and claim.claim_type in (
                ClaimType.SCOPED_RULE,
                ClaimType.ALWAYS_ON_RULE,
            ):
                scoped_claims.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination=f"instructions/{claim.scope}",
                        reason="scoped claim routed to .instructions.md",
                    )
                )
                continue

            # Environment prerequisites go to setup-steps
            if claim.claim_type == ClaimType.ENVIRONMENT_PREREQUISITE:
                env_claims.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="setup-steps",
                        reason="environment prerequisite routed to copilot-setup-steps.yml",
                    )
                )
                continue

            # Categorize by type
            if claim.claim_type == ClaimType.VALIDATED_COMMAND:
                command_claims.append(claim)
            elif claim.claim_type in (ClaimType.ALWAYS_ON_RULE, ClaimType.SCOPED_RULE):
                if claim.source_authority in _HIGH_AUTHORITY:
                    convention_claims.append(claim)
                else:
                    decisions.append(
                        ProjectionDecision(
                            claim_id=claim.id,
                            destination="excluded",
                            reason="low-authority convention excluded from thin copilot projection",
                        )
                    )
                    continue
            elif claim.claim_type == ClaimType.PERMISSION_RESTRICTION:
                guardrail_claims.append(claim)
            else:
                # Module boundaries, conflicts, skills — not projected
                continue

        # --- (a) copilot-instructions.md ---
        header = _render_generation_header(
            repo=repo,
            head=head,
            branch=branch_name,
            file_desc="copilot-instructions.md",
        )
        instructions_body = self._render_copilot_instructions(
            command_claims,
            convention_claims,
            guardrail_claims,
            env_claims,
            budget,
            decisions,
        )
        files[".github/copilot-instructions.md"] = header + "\n" + instructions_body

        # --- (b) .github/instructions/*.instructions.md ---
        if scoped_claims:
            scoped_files = self._render_scoped_instructions(scoped_claims)
            files.update(scoped_files)

        # --- (c) copilot-setup-steps.yml ---
        all_env_and_cmd = env_claims + command_claims
        setup_content, validation_errors = generate_setup_steps(
            all_env_and_cmd,
            repo=repo,
            head=head,
            branch=branch_name,
        )
        # Store setup-steps content and validation status in the files dict.
        # The validation errors are conveyed via the overflow_report.
        files[".github/workflows/copilot-setup-steps.yml"] = setup_content

        # --- (d) Tool allowlist ---
        allowlist = generate_tool_allowlist()
        files[".copilot-tool-allowlist.json"] = json.dumps(allowlist, indent=2) + "\n"

        # Track budget
        for claim in command_claims + convention_claims + guardrail_claims:
            budget.try_include(claim, f"- {claim.content}\n")

        # Build excluded claims list
        excluded: list[tuple[str, str]] = [
            (d.claim_id, d.reason) for d in decisions if d.destination == "excluded"
        ]

        # Overflow report
        overflow = budget.overflow_report
        overflow["decisions"] = [
            {"claim_id": d.claim_id, "destination": d.destination, "reason": d.reason}
            for d in decisions
        ]
        overflow["setup_steps_validation"] = {
            "valid": len(validation_errors) == 0,
            "errors": validation_errors,
        }

        return AdapterResult(
            files=files,
            excluded_claims=excluded,
            overflow_report=overflow,
        )

    def _render_copilot_instructions(
        self,
        commands: list[Claim],
        conventions: list[Claim],
        guardrails: list[Claim],
        env_claims: list[Claim],
        budget: BudgetTracker,
        decisions: list[ProjectionDecision],
    ) -> str:
        """Render copilot-instructions.md — thin, Copilot-specific content."""
        lines: list[str] = []

        # Restrictions first — Copilot runs autonomously, guardrails are critical
        destructive_guardrails = [g for g in guardrails if "destructive" in g.content.lower()]
        advisory_guardrails = [g for g in guardrails if "destructive" not in g.content.lower()]

        if destructive_guardrails:
            lines.append("## Restrictions\n")
            lines.append(
                "**Important**: This agent runs autonomously. "
                "The following operations require caution:\n"
            )
            for claim in destructive_guardrails:
                lines.append(f"- **WARNING**: {claim.content}")
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="copilot-instructions.md",
                        reason="destructive guardrail — prominent placement",
                    )
                )
            lines.append("")

        if advisory_guardrails:
            if not destructive_guardrails:
                lines.append("## Restrictions\n")
            for claim in advisory_guardrails:
                lines.append(f"- {claim.content}")
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="copilot-instructions.md",
                        reason="advisory guardrail in copilot-instructions.md",
                    )
                )
            lines.append("")

        # Key commands — only the most essential ones
        key_commands = [
            c
            for c in commands
            if c.risk_class in (RiskClass.TEST_EXECUTION, RiskClass.SAFE_READONLY)
            or any(tag in c.applicability for tag in ("test", "lint", "build"))
        ]
        if key_commands:
            lines.append("## Key Commands\n")
            for claim in key_commands:
                lines.append(f"- `{claim.content}`")
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="copilot-instructions.md",
                        reason="key command in copilot-instructions.md",
                    )
                )
            lines.append("")

        # Critical conventions — highest confidence only, brief
        top_conventions = conventions[:10]  # Limit to avoid bloat
        if top_conventions:
            lines.append("## Critical Conventions\n")
            for claim in top_conventions:
                lines.append(f"- {claim.content}")
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="copilot-instructions.md",
                        reason="high-confidence convention in copilot-instructions.md",
                    )
                )
            lines.append("")

        # Environment notes — brief reference to setup-steps
        if env_claims:
            lines.append("## Environment\n")
            lines.append(
                "Environment setup is handled by `copilot-setup-steps.yml`. "
                "The following are available after setup:\n"
            )
            lines.extend(f"- {claim.content}" for claim in env_claims[:5])
            lines.append("")

        return "\n".join(lines)

    def _render_scoped_instructions(
        self,
        claims: list[Claim],
    ) -> dict[str, str]:
        """Render .github/instructions/*.instructions.md files."""
        files: dict[str, str] = {}

        # Group by scope
        groups: dict[str, list[Claim]] = defaultdict(list)
        for claim in claims:
            scope = claim.scope.strip("/")
            key = re.sub(r"[^a-z0-9]+", "-", scope.lower()).strip("-")
            if not key:
                key = "general"
            groups[key].append(claim)

        for group_key, group_claims in sorted(groups.items()):
            sorted_group = _stable_sort_claims(group_claims)
            # Collect paths for applyTo frontmatter
            paths = sorted({c.scope for c in sorted_group})
            # Use the first (most specific) path for applyTo
            apply_to = paths[0] if len(paths) == 1 else f"{{{','.join(paths)}}}"

            content_lines: list[str] = [
                "---",
                f'applyTo: "{apply_to}"',
                "---",
                "",
            ]
            content_lines.extend(f"- {claim.content}" for claim in sorted_group)
            content_lines.append("")
            files[f".github/instructions/{group_key}.instructions.md"] = "\n".join(content_lines)

        return files
