"""Cursor adapter — Alpha export-only projection for .cursor/rules/*.md.

Generates rule files with YAML frontmatter (description, globs, alwaysApply).

Key constraints:
- alwaysApply: true for repo-wide conventions; false + globs for scoped rules.
- No native skills — skill playbooks are inlined into rule content.
- No native permissions — guardrails are advisory text only.
- All generated filenames prefixed with rkp- to distinguish from user-created rules.
- Generation header goes in the YAML description field (Cursor reads frontmatter).
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime

from rkp.core.models import Claim
from rkp.core.types import ClaimType, SourceAuthority, source_authority_precedence
from rkp.projection.adapters.base import AdapterResult
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import HostCapability

_HIGH_AUTHORITY = frozenset(
    {
        SourceAuthority.HUMAN_OVERRIDE,
        SourceAuthority.DECLARED_REVIEWED,
        SourceAuthority.EXECUTABLE_CONFIG,
        SourceAuthority.CI_OBSERVED,
        SourceAuthority.INFERRED_HIGH,
    }
)

_GENERATION_SUFFIX = "Generated by RKP — DO NOT EDIT. Corrections: rkp review"


def _stable_sort_claims(claims: list[Claim]) -> list[Claim]:
    """Sort claims deterministically: authority ASC, scope ASC, type ASC, id ASC."""
    return sorted(
        claims,
        key=lambda c: (
            source_authority_precedence(c.source_authority),
            c.scope,
            c.claim_type.value,
            c.id,
        ),
    )


def _gen_description(file_desc: str, repo: str, head: str) -> str:
    """Build a YAML description field with provenance."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f"[RKP] {file_desc} | repo:{repo} head:{head[:8]} {ts}"


def _scope_to_globs(scope: str) -> list[str]:
    """Convert a claim scope to Cursor glob patterns."""
    scope = scope.strip("/")
    if scope == "**" or not scope:
        return []
    if "*" in scope:
        return [scope]
    return [f"{scope}/**"]


def _scope_to_key(scope: str) -> str:
    """Convert a scope path to a safe filename key."""
    scope = scope.strip("/")
    key = re.sub(r"[^a-z0-9]+", "-", scope.lower()).strip("-")
    return key or "general"


@dataclass(frozen=True)
class ProjectionDecision:
    """Why a claim ended up where it did."""

    claim_id: str
    destination: str
    reason: str


class CursorAdapter:
    """Generates .cursor/rules/*.md from claims (Alpha — export-only)."""

    def project(
        self,
        claims: list[Claim],
        capability: HostCapability,
        budget: BudgetTracker,
    ) -> AdapterResult:
        """Project claims into .cursor/rules/ files."""
        sorted_claims = _stable_sort_claims(claims)
        decisions: list[ProjectionDecision] = []
        files: dict[str, str] = {}

        if not sorted_claims:
            return AdapterResult(
                files={}, excluded_claims=[], overflow_report=budget.overflow_report
            )

        repo = sorted_claims[0].repo_id
        head = sorted_claims[0].provenance.repo_head

        # Categorize claims
        command_claims: list[Claim] = []
        convention_claims: list[Claim] = []
        guardrail_claims: list[Claim] = []
        setup_claims: list[Claim] = []
        scoped_claims: list[Claim] = []
        skill_claims: list[Claim] = []

        for claim in sorted_claims:
            # Scoped rules → separate files with globs
            if claim.scope != "**" and claim.claim_type in (
                ClaimType.SCOPED_RULE,
                ClaimType.ALWAYS_ON_RULE,
            ):
                scoped_claims.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination=f"rules/rkp-{_scope_to_key(claim.scope)}",
                        reason="scoped claim routed to glob-targeted rule file",
                    )
                )
                continue

            if claim.claim_type == ClaimType.VALIDATED_COMMAND:
                command_claims.append(claim)
            elif claim.claim_type == ClaimType.ENVIRONMENT_PREREQUISITE:
                setup_claims.append(claim)
            elif claim.claim_type == ClaimType.PERMISSION_RESTRICTION:
                guardrail_claims.append(claim)
            elif claim.claim_type == ClaimType.SKILL_PLAYBOOK:
                skill_claims.append(claim)
            elif claim.claim_type in (ClaimType.ALWAYS_ON_RULE, ClaimType.SCOPED_RULE):
                if claim.source_authority in _HIGH_AUTHORITY:
                    convention_claims.append(claim)
                else:
                    decisions.append(
                        ProjectionDecision(
                            claim_id=claim.id,
                            destination="excluded",
                            reason="low-authority convention excluded from Cursor projection",
                        )
                    )
            # Module boundaries, conflicts — not projected

        # --- rkp-guardrails.md (alwaysApply: true) ---
        if guardrail_claims:
            lines: list[str] = []
            lines.append("## Restrictions\n")
            lines.append("The following operations require caution:\n")
            for claim in guardrail_claims:
                lines.append(f"- {claim.content}")
                budget.try_include(claim, claim.content)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="rules/rkp-guardrails",
                        reason="guardrail in rkp-guardrails.md",
                    )
                )
            body = "\n".join(lines) + "\n"
            desc = _gen_description("Guardrails", repo, head)
            files[".cursor/rules/rkp-guardrails.md"] = _render_always_apply(desc, body)

        # --- rkp-commands.md (alwaysApply: true) ---
        if command_claims:
            lines = []
            lines.append("## Commands\n")
            for claim in command_claims:
                risk_label = claim.risk_class.value if claim.risk_class else "build"
                lines.append(f"- `{claim.content}` ({risk_label})")
                budget.try_include(claim, claim.content)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="rules/rkp-commands",
                        reason="command in rkp-commands.md",
                    )
                )
            body = "\n".join(lines) + "\n"
            desc = _gen_description("Commands", repo, head)
            files[".cursor/rules/rkp-commands.md"] = _render_always_apply(desc, body)

        # --- rkp-conventions.md (alwaysApply: true) ---
        conv_body_claims = list(convention_claims)
        # Inline skill playbooks into conventions (Cursor has no separate skills)
        if skill_claims:
            conv_body_claims.extend(skill_claims)
            decisions.extend(
                ProjectionDecision(
                    claim_id=claim.id,
                    destination="rules/rkp-conventions",
                    reason="skill-playbook inlined into conventions (no Cursor skills)",
                )
                for claim in skill_claims
            )

        if conv_body_claims:
            lines = []
            lines.append("## Conventions\n")
            for claim in convention_claims:
                lines.append(f"- {claim.content}")
                budget.try_include(claim, claim.content)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="rules/rkp-conventions",
                        reason="convention in rkp-conventions.md",
                    )
                )
            if skill_claims:
                lines.append("")
                lines.append("## Procedures\n")
                for claim in skill_claims:
                    lines.append(f"### {claim.scope}\n")
                    lines.append(claim.content)
                    lines.append("")
                    budget.try_include(claim, claim.content)
            body = "\n".join(lines) + "\n"
            desc = _gen_description("Conventions", repo, head)
            files[".cursor/rules/rkp-conventions.md"] = _render_always_apply(desc, body)

        # --- rkp-setup.md (alwaysApply: true) — environment prerequisites ---
        if setup_claims:
            lines = []
            lines.append("## Environment Setup\n")
            for claim in setup_claims:
                lines.append(f"- {claim.content}")
                budget.try_include(claim, claim.content)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="rules/rkp-setup",
                        reason="environment prerequisite in rkp-setup.md",
                    )
                )
            body = "\n".join(lines) + "\n"
            desc = _gen_description("Setup", repo, head)
            files[".cursor/rules/rkp-setup.md"] = _render_always_apply(desc, body)

        # --- Scoped rule files (alwaysApply: false + globs) ---
        if scoped_claims:
            groups: dict[str, list[Claim]] = defaultdict(list)
            for claim in scoped_claims:
                key = _scope_to_key(claim.scope)
                groups[key].append(claim)

            for group_key, group_claims in sorted(groups.items()):
                group_sorted = _stable_sort_claims(group_claims)
                all_globs: list[str] = []
                for c in group_sorted:
                    all_globs.extend(_scope_to_globs(c.scope))
                # Deduplicate and sort globs
                unique_globs = sorted(set(all_globs))
                if not unique_globs:
                    unique_globs = [f"{group_key}/**"]

                lines = []
                for claim in group_sorted:
                    lines.append(f"- {claim.content}")
                    budget.try_include(claim, claim.content)
                body = "\n".join(lines) + "\n"
                desc = _gen_description(f"Scoped rules for {group_key}", repo, head)
                files[f".cursor/rules/rkp-{group_key}.md"] = _render_scoped(
                    desc, unique_globs, body
                )

        # Build result
        excluded: list[tuple[str, str]] = [
            (d.claim_id, d.reason) for d in decisions if d.destination == "excluded"
        ]
        overflow = budget.overflow_report
        overflow["decisions"] = [
            {"claim_id": d.claim_id, "destination": d.destination, "reason": d.reason}
            for d in decisions
        ]
        return AdapterResult(files=files, excluded_claims=excluded, overflow_report=overflow)


def _render_always_apply(description: str, body: str) -> str:
    """Render a Cursor rule file with alwaysApply: true."""
    return f"""---
description: "{description}"
alwaysApply: true
---

{body}"""


def _render_scoped(description: str, globs: list[str], body: str) -> str:
    """Render a Cursor rule file with alwaysApply: false + globs."""
    glob_lines = "\n".join(f'  - "{g}"' for g in globs)
    return f"""---
description: "{description}"
globs:
{glob_lines}
alwaysApply: false
---

{body}"""
