"""Windsurf adapter — Alpha export-only projection for .windsurf/rules/*.md.

Generates rule files with YAML frontmatter (trigger: always_on or trigger: glob).

Key constraints:
- trigger: always_on for repo-wide rules; trigger: glob for path-scoped rules.
- Hard budget: 6K characters per global rule file, 12K total workspace budget.
- Windsurf auto-reads AGENTS.md — content in AGENTS.md must be deduplicated.
- Skills, workflows, and memories deferred (Alpha scope — rules only).
- All generated filenames prefixed with rkp-.
- Generation header in content body (frontmatter kept minimal for trigger/glob).
"""

from __future__ import annotations

import re
from collections import defaultdict
from dataclasses import dataclass
from datetime import UTC, datetime

from rkp.core.models import Claim
from rkp.core.types import ClaimType, SourceAuthority, source_authority_precedence
from rkp.projection.adapters.base import AdapterResult
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import HostCapability

_HIGH_AUTHORITY = frozenset(
    {
        SourceAuthority.HUMAN_OVERRIDE,
        SourceAuthority.DECLARED_REVIEWED,
        SourceAuthority.EXECUTABLE_CONFIG,
        SourceAuthority.CI_OBSERVED,
        SourceAuthority.INFERRED_HIGH,
    }
)

# Per-file character limit for Windsurf global rules.
_PER_FILE_CHAR_LIMIT = 6144

# Total workspace character limit across all rule files.
_WORKSPACE_CHAR_LIMIT = 12288

# Priority order for budget-constrained inclusion.
# Lower number = higher priority.
_CLAIM_TYPE_PRIORITY: dict[ClaimType, int] = {
    ClaimType.PERMISSION_RESTRICTION: 0,  # guardrails first (safety)
    ClaimType.VALIDATED_COMMAND: 1,  # commands (operational)
    ClaimType.ENVIRONMENT_PREREQUISITE: 2,  # setup
    ClaimType.ALWAYS_ON_RULE: 3,  # conventions
    ClaimType.SCOPED_RULE: 3,
    ClaimType.SKILL_PLAYBOOK: 4,  # deferred in Alpha
    ClaimType.MODULE_BOUNDARY: 5,
    ClaimType.CONFLICT: 5,
}


def _stable_sort_claims(claims: list[Claim]) -> list[Claim]:
    """Sort claims deterministically: authority ASC, scope ASC, type ASC, id ASC."""
    return sorted(
        claims,
        key=lambda c: (
            source_authority_precedence(c.source_authority),
            c.scope,
            c.claim_type.value,
            c.id,
        ),
    )


def _scope_to_key(scope: str) -> str:
    """Convert a scope path to a safe filename key."""
    scope = scope.strip("/")
    key = re.sub(r"[^a-z0-9]+", "-", scope.lower()).strip("-")
    return key or "general"


def _scope_to_glob(scope: str) -> str:
    """Convert a claim scope to a Windsurf glob pattern."""
    scope = scope.strip("/")
    if "*" in scope:
        return scope
    return f"{scope}/**"


def _gen_header(file_desc: str, repo: str, head: str) -> str:
    """Build a generation header comment for the content body."""
    ts = datetime.now(UTC).strftime("%Y-%m-%dT%H:%M:%SZ")
    return (
        f"<!-- Generated by RKP ({file_desc}) | repo:{repo} head:{head[:8]} "
        f"{ts} | DO NOT EDIT — corrections: rkp review -->\n"
    )


@dataclass(frozen=True)
class ProjectionDecision:
    """Why a claim ended up where it did."""

    claim_id: str
    destination: str
    reason: str


class WindsurfAdapter:
    """Generates .windsurf/rules/*.md from claims (Alpha — export-only).

    Budget enforcement:
    - 6K characters per global rule file
    - 12K characters total across all workspace rules
    - Priority: guardrails > commands > conventions
    """

    def __init__(self, agents_md_claim_ids: frozenset[str] | None = None) -> None:
        """Initialize with optional set of claim IDs already in AGENTS.md.

        Claims in agents_md_claim_ids are excluded to avoid duplication
        (Windsurf auto-reads AGENTS.md).
        """
        self._agents_md_ids: frozenset[str] = agents_md_claim_ids or frozenset()

    def project(
        self,
        claims: list[Claim],
        capability: HostCapability,
        budget: BudgetTracker,
    ) -> AdapterResult:
        """Project claims into .windsurf/rules/ files."""
        sorted_claims = _stable_sort_claims(claims)
        decisions: list[ProjectionDecision] = []
        files: dict[str, str] = {}

        if not sorted_claims:
            return AdapterResult(
                files={}, excluded_claims=[], overflow_report=budget.overflow_report
            )

        repo = sorted_claims[0].repo_id
        head = sorted_claims[0].provenance.repo_head

        workspace_chars_used = 0

        # Filter out claims already in AGENTS.md
        deduplicated: list[Claim] = []
        for claim in sorted_claims:
            if claim.id in self._agents_md_ids:
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="excluded",
                        reason="already projected to AGENTS.md (Windsurf auto-reads)",
                    )
                )
                continue
            deduplicated.append(claim)

        # Categorize claims
        command_claims: list[Claim] = []
        convention_claims: list[Claim] = []
        guardrail_claims: list[Claim] = []
        setup_claims: list[Claim] = []
        scoped_claims: list[Claim] = []

        for claim in deduplicated:
            # Scoped rules → separate files with trigger: glob
            if claim.scope != "**" and claim.claim_type in (
                ClaimType.SCOPED_RULE,
                ClaimType.ALWAYS_ON_RULE,
            ):
                scoped_claims.append(claim)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination=f"rules/rkp-{_scope_to_key(claim.scope)}",
                        reason="scoped claim routed to glob-triggered rule file",
                    )
                )
                continue

            if claim.claim_type == ClaimType.VALIDATED_COMMAND:
                command_claims.append(claim)
            elif claim.claim_type == ClaimType.ENVIRONMENT_PREREQUISITE:
                setup_claims.append(claim)
            elif claim.claim_type == ClaimType.PERMISSION_RESTRICTION:
                guardrail_claims.append(claim)
            elif claim.claim_type == ClaimType.SKILL_PLAYBOOK:
                # Deferred in Alpha
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="excluded",
                        reason="skill-playbook deferred in Windsurf Alpha",
                    )
                )
            elif claim.claim_type in (ClaimType.ALWAYS_ON_RULE, ClaimType.SCOPED_RULE):
                if claim.source_authority in _HIGH_AUTHORITY:
                    convention_claims.append(claim)
                else:
                    decisions.append(
                        ProjectionDecision(
                            claim_id=claim.id,
                            destination="excluded",
                            reason="low-authority convention excluded from Windsurf projection",
                        )
                    )
            # Module boundaries, conflicts — not projected

        # Build files in priority order: guardrails > commands > setup > conventions
        # Each file must fit within 6K per file AND 12K total workspace.

        def _try_add_file(
            rel_path: str,
            content: str,
            file_claims: list[Claim],
            dest_name: str,
        ) -> bool:
            """Try to add a file within budget. Returns True if added."""
            nonlocal workspace_chars_used
            char_count = len(content)

            if char_count > _PER_FILE_CHAR_LIMIT:
                decisions.extend(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="excluded",
                        reason=f"file exceeds 6K per-file limit ({char_count} chars)",
                    )
                    for claim in file_claims
                )
                return False

            if workspace_chars_used + char_count > _WORKSPACE_CHAR_LIMIT:
                decisions.extend(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination="excluded",
                        reason=f"workspace budget exceeded ({workspace_chars_used + char_count} > {_WORKSPACE_CHAR_LIMIT})",
                    )
                    for claim in file_claims
                )
                return False

            files[rel_path] = content
            workspace_chars_used += char_count
            budget.add_workspace_bytes(len(content.encode("utf-8")))
            for claim in file_claims:
                budget.try_include(claim, claim.content)
                decisions.append(
                    ProjectionDecision(
                        claim_id=claim.id,
                        destination=dest_name,
                        reason=f"included in {dest_name}",
                    )
                )
            return True

        # --- rkp-guardrails.md (trigger: always_on) ---
        if guardrail_claims:
            header = _gen_header("Guardrails", repo, head)
            lines = [header, "## Restrictions\n"]
            lines.extend(f"- {claim.content}" for claim in guardrail_claims)
            body = "\n".join(lines) + "\n"
            content = _render_always_on(body)
            _try_add_file(
                ".windsurf/rules/rkp-guardrails.md",
                content,
                guardrail_claims,
                "rules/rkp-guardrails",
            )

        # --- rkp-commands.md (trigger: always_on) ---
        if command_claims:
            header = _gen_header("Commands", repo, head)
            lines = [header, "## Commands\n"]
            for claim in command_claims:
                risk_label = claim.risk_class.value if claim.risk_class else "build"
                lines.append(f"- `{claim.content}` ({risk_label})")
            body = "\n".join(lines) + "\n"
            content = _render_always_on(body)
            _try_add_file(
                ".windsurf/rules/rkp-commands.md",
                content,
                command_claims,
                "rules/rkp-commands",
            )

        # --- rkp-setup.md (trigger: always_on) — environment prerequisites ---
        if setup_claims:
            header = _gen_header("Setup", repo, head)
            lines = [header, "## Environment Setup\n"]
            for claim in setup_claims:
                lines.append(f"- {claim.content}")
            body = "\n".join(lines) + "\n"
            content = _render_always_on(body)
            _try_add_file(
                ".windsurf/rules/rkp-setup.md",
                content,
                setup_claims,
                "rules/rkp-setup",
            )

        # --- rkp-conventions.md (trigger: always_on) ---
        if convention_claims:
            header = _gen_header("Conventions", repo, head)
            lines = [header, "## Conventions\n"]
            for claim in convention_claims:
                lines.append(f"- {claim.content}")
            body = "\n".join(lines) + "\n"
            content = _render_always_on(body)
            _try_add_file(
                ".windsurf/rules/rkp-conventions.md",
                content,
                convention_claims,
                "rules/rkp-conventions",
            )

        # --- Scoped rule files (trigger: glob) ---
        if scoped_claims:
            groups: dict[str, list[Claim]] = defaultdict(list)
            for claim in scoped_claims:
                key = _scope_to_key(claim.scope)
                groups[key].append(claim)

            for group_key, group_claims in sorted(groups.items()):
                group_sorted = _stable_sort_claims(group_claims)
                # Use the first scope's glob
                glob_pattern = _scope_to_glob(group_sorted[0].scope)

                header = _gen_header(f"Scoped: {group_key}", repo, head)
                lines = [header]
                for claim in group_sorted:
                    lines.append(f"- {claim.content}")
                body = "\n".join(lines) + "\n"
                content = _render_glob(glob_pattern, body)
                _try_add_file(
                    f".windsurf/rules/rkp-{group_key}.md",
                    content,
                    group_sorted,
                    f"rules/rkp-{group_key}",
                )

        # Build result
        excluded: list[tuple[str, str]] = [
            (d.claim_id, d.reason) for d in decisions if d.destination == "excluded"
        ]
        overflow = budget.overflow_report
        overflow["decisions"] = [
            {"claim_id": d.claim_id, "destination": d.destination, "reason": d.reason}
            for d in decisions
        ]
        overflow["windsurf_budget"] = {
            "per_file_limit": _PER_FILE_CHAR_LIMIT,
            "workspace_limit": _WORKSPACE_CHAR_LIMIT,
            "workspace_used": workspace_chars_used,
            "workspace_remaining": _WORKSPACE_CHAR_LIMIT - workspace_chars_used,
        }
        return AdapterResult(files=files, excluded_claims=excluded, overflow_report=overflow)


def _render_always_on(body: str) -> str:
    """Render a Windsurf rule file with trigger: always_on."""
    return f"""---
trigger: always_on
---

{body}"""


def _render_glob(glob_pattern: str, body: str) -> str:
    """Render a Windsurf rule file with trigger: glob."""
    return f"""---
trigger: glob
glob: "{glob_pattern}"
---

{body}"""
