"""CLI integration tests."""

from __future__ import annotations

from pathlib import Path

from typer.testing import CliRunner

from rkp.cli.app import app

runner = CliRunner()


class TestPreviewCommand:
    def test_preview_on_fixture(self) -> None:
        """rkp preview --host codex on fixture repo produces non-empty output."""
        fixture_path = Path(__file__).parent.parent / "fixtures" / "simple_python"
        result = runner.invoke(app, ["--repo", str(fixture_path), "preview", "--host", "codex"])
        assert result.exit_code == 0
        assert "Generated by RKP" in result.stdout

    def test_preview_json_mode(self) -> None:
        """JSON mode works."""
        fixture_path = Path(__file__).parent.parent / "fixtures" / "simple_python"
        result = runner.invoke(
            app, ["--repo", str(fixture_path), "--json", "preview", "--host", "codex"]
        )
        assert result.exit_code == 0
        import json

        output = json.loads(result.stdout)
        assert "content" in output
        assert "host" in output

    def test_preview_unsupported_host(self) -> None:
        """Unsupported host returns error."""
        fixture_path = Path(__file__).parent.parent / "fixtures" / "simple_python"
        result = runner.invoke(app, ["--repo", str(fixture_path), "preview", "--host", "unknown"])
        assert result.exit_code == 2

    def test_preview_empty_repo(self, tmp_path: Path) -> None:
        """Preview on empty repo still produces output."""
        result = runner.invoke(app, ["--repo", str(tmp_path), "preview", "--host", "codex"])
        assert result.exit_code == 0
        assert "Generated by RKP" in result.stdout
