"""CLI integration tests for M6: --host claude preview."""

from __future__ import annotations

import json
from pathlib import Path

from typer.testing import CliRunner

from rkp.cli.app import app

runner = CliRunner()


class TestClaudePreview:
    def test_preview_claude_produces_output(self) -> None:
        """rkp preview --host claude → non-empty output with multiple sections."""
        fixture_path = Path(__file__).parent.parent / "fixtures" / "simple_python"
        result = runner.invoke(app, ["--repo", str(fixture_path), "preview", "--host", "claude"])
        assert result.exit_code == 0
        assert "CLAUDE.md" in result.stdout or "Generated by RKP" in result.stdout

    def test_preview_claude_json_mode(self) -> None:
        """rkp preview --host claude --json → valid JSON with all artifact types."""
        fixture_path = Path(__file__).parent.parent / "fixtures" / "simple_python"
        result = runner.invoke(
            app, ["--repo", str(fixture_path), "--json", "preview", "--host", "claude"]
        )
        assert result.exit_code == 0
        output = json.loads(result.stdout)
        assert output["host"] == "claude"
        assert "files" in output
        assert "CLAUDE.md" in output["files"]

    def test_preview_codex_still_works(self) -> None:
        """rkp preview --host codex → still works (no regression)."""
        fixture_path = Path(__file__).parent.parent / "fixtures" / "simple_python"
        result = runner.invoke(app, ["--repo", str(fixture_path), "preview", "--host", "codex"])
        assert result.exit_code == 0
        assert "Generated by RKP" in result.stdout

    def test_preview_empty_repo_claude(self, tmp_path: Path) -> None:
        """Preview --host claude on empty repo still produces output."""
        result = runner.invoke(app, ["--repo", str(tmp_path), "preview", "--host", "claude"])
        assert result.exit_code == 0
