"""Snapshot tests for AGENTS.md projection."""

from __future__ import annotations

import re
from dataclasses import replace

from rkp.core.claim_builder import ClaimBuilder
from rkp.core.types import ClaimType, RiskClass, Sensitivity, SourceAuthority
from rkp.projection.adapters.agents_md import AgentsMdAdapter
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import AGENTS_MD_CAPABILITY
from rkp.projection.engine import ProjectionPolicy, project


class TestAgentsMdProjection:
    def test_basic_projection(self, builder: ClaimBuilder) -> None:
        """Known claims produce expected AGENTS.md output."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=("pyproject.toml",),
            ),
            builder.build(
                content="ruff check .",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=("pyproject.toml",),
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)
        claims[1] = replace(claims[1], risk_class=RiskClass.SAFE_READONLY)

        adapter = AgentsMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, AGENTS_MD_CAPABILITY, policy)

        content = result.adapter_result.files["AGENTS.md"]
        assert "## Commands" in content
        assert "`pytest`" in content
        assert "`ruff check .`" in content
        assert "Generated by RKP v0.1.0" in content

    def test_deterministic_output(self, builder: ClaimBuilder) -> None:
        """Same claims produce identical output."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = AgentsMdAdapter()

        budget1 = BudgetTracker(hard_budget_bytes=32768)
        result1 = adapter.project(claims, AGENTS_MD_CAPABILITY, budget1)

        budget2 = BudgetTracker(hard_budget_bytes=32768)
        result2 = adapter.project(claims, AGENTS_MD_CAPABILITY, budget2)

        content1 = re.sub(r"timestamp: [^\s|]+", "timestamp: X", result1.files["AGENTS.md"])
        content2 = re.sub(r"timestamp: [^\s|]+", "timestamp: X", result2.files["AGENTS.md"])
        assert content1 == content2

    def test_sensitivity_filtering(self, builder: ClaimBuilder) -> None:
        """Local-only claims excluded from projection."""
        public_claim = builder.build(
            content="pytest",
            claim_type=ClaimType.VALIDATED_COMMAND,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            sensitivity=Sensitivity.PUBLIC,
            confidence=1.0,
        )
        local_claim = builder.build(
            content="secret-command",
            claim_type=ClaimType.VALIDATED_COMMAND,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            sensitivity=Sensitivity.LOCAL_ONLY,
            confidence=1.0,
        )
        public_claim = replace(public_claim, risk_class=RiskClass.TEST_EXECUTION)
        local_claim = replace(local_claim, risk_class=RiskClass.BUILD)

        adapter = AgentsMdAdapter()
        policy = ProjectionPolicy()
        result = project([public_claim, local_claim], adapter, AGENTS_MD_CAPABILITY, policy)

        content = result.adapter_result.files["AGENTS.md"]
        assert "`pytest`" in content
        assert "secret-command" not in content
        assert len(result.excluded_sensitive) == 1

    def test_budget_overflow(self, builder: ClaimBuilder) -> None:
        """Too many claims for budget triggers overflow."""
        claims = []
        for i in range(100):
            claim = builder.build(
                content=f"very-long-command-name-for-testing-overflow-behavior-{i}",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            )
            claims.append(replace(claim, risk_class=RiskClass.BUILD))

        adapter = AgentsMdAdapter()
        budget = BudgetTracker(hard_budget_bytes=500)
        adapter.project(claims, AGENTS_MD_CAPABILITY, budget)

        assert len(budget.omitted) > 0

    def test_empty_claims(self, builder: ClaimBuilder) -> None:
        """Empty claims produce minimal output."""
        adapter = AgentsMdAdapter()
        policy = ProjectionPolicy()
        result = project([], adapter, AGENTS_MD_CAPABILITY, policy)

        content = result.adapter_result.files["AGENTS.md"]
        assert "Generated by RKP" in content

    def test_conventions_in_projection(self, builder: ClaimBuilder) -> None:
        """Convention claims with inferred-high authority appear in AGENTS.md."""
        claims = [
            builder.build(
                content="Use snake_case for function names (100% consistency)",
                claim_type=ClaimType.ALWAYS_ON_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=1.0,
                applicability=("all",),
            ),
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            ),
        ]
        claims[1] = replace(claims[1], risk_class=RiskClass.TEST_EXECUTION)

        adapter = AgentsMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, AGENTS_MD_CAPABILITY, policy)

        content = result.adapter_result.files["AGENTS.md"]
        assert "## Conventions" in content
        assert "snake_case" in content
        assert "## Commands" in content

    def test_low_confidence_conventions_excluded(self, builder: ClaimBuilder) -> None:
        """Conventions with inferred-low authority excluded from always-on projection."""
        claims = [
            builder.build(
                content="Weak convention that should be excluded",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_LOW,
                confidence=0.85,
                applicability=("all",),
            ),
        ]

        adapter = AgentsMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, AGENTS_MD_CAPABILITY, policy)

        content = result.adapter_result.files["AGENTS.md"]
        assert "Weak convention" not in content
