"""Snapshot tests for CLAUDE.md projection and multi-file adapter results."""

from __future__ import annotations

import re
from dataclasses import replace

from rkp.core.claim_builder import ClaimBuilder
from rkp.core.types import ClaimType, RiskClass, SourceAuthority
from rkp.projection.adapters.agents_md import AgentsMdAdapter
from rkp.projection.adapters.claude_md import ClaudeMdAdapter
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import AGENTS_MD_CAPABILITY, CLAUDE_CODE_CAPABILITY
from rkp.projection.engine import ProjectionPolicy, project


class TestMultiFileProjectionResult:
    def test_claude_adapter_multi_file(self, builder: ClaimBuilder) -> None:
        """Multi-file result from Claude adapter integrates cleanly with engine."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=("pyproject.toml",),
            ),
            builder.build(
                content="Use snake_case",
                claim_type=ClaimType.ALWAYS_ON_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=1.0,
                applicability=("all",),
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, CLAUDE_CODE_CAPABILITY, policy)

        # Result should have proper structure
        assert result.adapter_result is not None
        assert isinstance(result.adapter_result.files, dict)
        assert "CLAUDE.md" in result.adapter_result.files
        assert result.adapter_result.overflow_report is not None

    def test_agents_md_still_works(self, builder: ClaimBuilder) -> None:
        """AGENTS.md adapter still works (no regression from multi-file support)."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=("pyproject.toml",),
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = AgentsMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, AGENTS_MD_CAPABILITY, policy)

        assert "AGENTS.md" in result.adapter_result.files
        content = result.adapter_result.files["AGENTS.md"]
        assert "`pytest`" in content
        assert "Generated by RKP" in content

    def test_agents_md_determinism_preserved(self, builder: ClaimBuilder) -> None:
        """AGENTS.md adapter determinism preserved after infrastructure changes."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = AgentsMdAdapter()

        budget1 = BudgetTracker(hard_budget_bytes=32768)
        result1 = adapter.project(claims, AGENTS_MD_CAPABILITY, budget1)

        budget2 = BudgetTracker(hard_budget_bytes=32768)
        result2 = adapter.project(claims, AGENTS_MD_CAPABILITY, budget2)

        content1 = re.sub(r"timestamp: [^\s|]+", "timestamp: X", result1.files["AGENTS.md"])
        content2 = re.sub(r"timestamp: [^\s|]+", "timestamp: X", result2.files["AGENTS.md"])
        assert content1 == content2

    def test_budget_tracker_optional_hard_budget(self) -> None:
        """BudgetTracker with None hard_budget_bytes works correctly."""
        budget = BudgetTracker(soft_budget_lines=200)
        assert budget.hard_budget_bytes is None

        from rkp.core.claim_builder import ClaimBuilder

        b = ClaimBuilder(repo_id="test", branch="main")
        claim = b.build(
            content="test",
            claim_type=ClaimType.VALIDATED_COMMAND,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            confidence=1.0,
        )

        # Should not raise — no hard byte limit
        result = budget.try_include(claim, "some content\n")
        assert result is True
        assert budget.current_bytes > 0

    def test_budget_tracker_no_hard_limit_allows_all(self) -> None:
        """BudgetTracker with no hard limit allows all claims."""
        budget = BudgetTracker(soft_budget_lines=200)

        b = ClaimBuilder(repo_id="test", branch="main")
        claim = b.build(
            content="large claim " * 100,
            claim_type=ClaimType.VALIDATED_COMMAND,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            confidence=1.0,
        )

        result = budget.try_include(claim, "large content " * 100)
        assert result is True
        assert len(budget.omitted) == 0
