"""Snapshot tests for Copilot projection."""

from __future__ import annotations

import re
from dataclasses import replace

import yaml

from rkp.core.claim_builder import ClaimBuilder
from rkp.core.types import ClaimType, RiskClass, Sensitivity, SourceAuthority
from rkp.projection.adapters.copilot import CopilotAdapter
from rkp.projection.capability_matrix import COPILOT_CAPABILITY
from rkp.projection.engine import ProjectionPolicy, project


class TestCopilotProjectionSnapshots:
    def test_copilot_instructions_snapshot(self, builder: ClaimBuilder) -> None:
        """Known claims produce expected copilot-instructions.md."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                    evidence=("pyproject.toml",),
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
            replace(
                builder.build(
                    content="ruff check .",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                    evidence=("pyproject.toml",),
                ),
                risk_class=RiskClass.SAFE_READONLY,
            ),
            builder.build(
                content="Use snake_case for function names",
                claim_type=ClaimType.ALWAYS_ON_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.95,
                applicability=("all",),
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        content = result.adapter_result.files[".github/copilot-instructions.md"]

        # Stable structure checks (not timestamp-dependent)
        assert "Generated by RKP v0.1.0" in content
        assert "## Key Commands" in content
        assert "`pytest`" in content
        assert "`ruff check .`" in content
        assert "## Critical Conventions" in content
        assert "snake_case" in content

    def test_copilot_setup_steps_snapshot(self, builder: ClaimBuilder) -> None:
        """Known claims produce expected copilot-setup-steps.yml."""
        claims = [
            builder.build(
                content="Python 3.12",
                claim_type=ClaimType.ENVIRONMENT_PREREQUISITE,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        content = result.adapter_result.files[".github/workflows/copilot-setup-steps.yml"]

        # Strip the header comments for YAML parsing
        yaml_content = "\n".join(line for line in content.split("\n") if not line.startswith("#"))
        parsed = yaml.safe_load(yaml_content)
        assert parsed is not None

        # Verify structure
        assert parsed["name"] == "Copilot Setup Steps"
        job = parsed["jobs"]["copilot-setup-steps"]
        assert job["runs-on"] == "ubuntu-latest"
        assert job["timeout-minutes"] <= 59

        # Verify setup-python step
        steps = job["steps"]
        setup_python = [s for s in steps if "setup-python" in s.get("uses", "")]
        assert len(setup_python) == 1
        assert setup_python[0]["with"]["python-version"] == "3.12"

    def test_setup_steps_snapshot_valid_yaml(self, builder: ClaimBuilder) -> None:
        """Setup-steps snapshot is valid YAML."""
        claims = [
            builder.build(
                content="Python 3.12",
                claim_type=ClaimType.ENVIRONMENT_PREREQUISITE,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        content = result.adapter_result.files[".github/workflows/copilot-setup-steps.yml"]
        # Should parse without error — strip comment header first
        yaml_lines = [line for line in content.split("\n") if not line.startswith("#")]
        parsed = yaml.safe_load("\n".join(yaml_lines))
        assert isinstance(parsed, dict)

    def test_sensitivity_local_only_excluded(self, builder: ClaimBuilder) -> None:
        """local-only claims are excluded from all Copilot outputs."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
            replace(
                builder.build(
                    content="secret-local-tool",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                sensitivity=Sensitivity.LOCAL_ONLY,
                risk_class=RiskClass.TEST_EXECUTION,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        # local-only claim excluded
        assert len(result.excluded_sensitive) == 1

        # Not in any file
        for content in result.adapter_result.files.values():
            assert "secret-local-tool" not in content

    def test_deterministic_output(self, builder: ClaimBuilder) -> None:
        """Same claims produce identical output (modulo timestamps)."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()

        result1 = project(claims, adapter, COPILOT_CAPABILITY, policy)
        result2 = project(claims, adapter, COPILOT_CAPABILITY, policy)

        # Same file keys
        assert set(result1.adapter_result.files.keys()) == set(result2.adapter_result.files.keys())

        # Content identical (except timestamps)
        ts_pattern = re.compile(r"\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z")
        for key in result1.adapter_result.files:
            c1 = ts_pattern.sub("TIMESTAMP", result1.adapter_result.files[key])
            c2 = ts_pattern.sub("TIMESTAMP", result2.adapter_result.files[key])
            assert c1 == c2, f"Non-deterministic output in {key}"
