"""rkp init — bootstrap RKP on a repository."""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import typer

from rkp.cli.app import AppState
from rkp.cli.ui.output import console, print_error, print_info, print_json
from rkp.cli.ui.tables import render_init_summary
from rkp.core.config import is_excluded_path
from rkp.core.types import ClaimType, ReviewState

# Languages in the launch support envelope.
_SUPPORTED_EXTENSIONS: dict[str, str] = {
    ".py": "Python",
    ".js": "JavaScript",
    ".jsx": "JavaScript",
    ".ts": "TypeScript",
    ".tsx": "TypeScript",
}

# Languages detected but not fully analyzed.
_UNSUPPORTED_EXTENSIONS: dict[str, str] = {
    ".go": "Go",
    ".rs": "Rust",
    ".java": "Java",
    ".rb": "Ruby",
    ".cs": "C#",
    ".cpp": "C++",
    ".c": "C",
    ".swift": "Swift",
    ".kt": "Kotlin",
    ".php": "PHP",
}

# Directories excluded from language detection.
_EXCLUDE_DIRS = (
    "vendor",
    "node_modules",
    "dist",
    "build",
    "__pycache__",
    ".git",
    ".venv",
    "venv",
    ".tox",
    ".nox",
    ".rkp",
    ".next",
    "out",
    "coverage",
)


def detect_languages(
    repo_path: Path,
    *,
    excluded_dirs: tuple[str, ...] = _EXCLUDE_DIRS,
) -> tuple[set[str], set[str]]:
    """Scan repo for supported and unsupported languages.

    Returns (supported_language_names, unsupported_language_names).
    """
    supported: set[str] = set()
    unsupported: set[str] = set()

    for item in _walk_source_files(repo_path, excluded_dirs=excluded_dirs):
        suffix = item.suffix.lower()
        if suffix in _SUPPORTED_EXTENSIONS:
            supported.add(_SUPPORTED_EXTENSIONS[suffix])
        elif suffix in _UNSUPPORTED_EXTENSIONS:
            unsupported.add(_UNSUPPORTED_EXTENSIONS[suffix])

    return supported, unsupported


def _walk_source_files(
    repo_path: Path,
    *,
    excluded_dirs: tuple[str, ...] = _EXCLUDE_DIRS,
) -> list[Path]:
    """Walk the repo for source files, respecting exclusions."""
    files: list[Path] = []
    all_extensions = set(_SUPPORTED_EXTENSIONS.keys()) | set(_UNSUPPORTED_EXTENSIONS.keys())

    try:
        for item in repo_path.rglob("*"):
            rel_path = item.relative_to(repo_path)
            if is_excluded_path(rel_path, excluded_dirs):
                continue
            if item.is_file() and item.suffix.lower() in all_extensions:
                files.append(item)
    except PermissionError:
        pass

    return files


def _write_default_config(rkp_dir: Path, supported_langs: set[str]) -> Path:
    """Write default .rkp/config.yaml."""
    config_path = rkp_dir / "config.yaml"
    langs_str = ", ".join(sorted(supported_langs)) if supported_langs else "none detected"
    config_path.write_text(
        f"# RKP configuration\n"
        f"# Auto-generated by rkp init\n"
        f"# discovery.exclude_dirs accepts either simple directory names (dist)\n"
        f"# or relative paths (tests/fixtures)\n"
        f"\n"
        f"support_envelope:\n"
        f"  languages: [{langs_str}]\n"
        f"\n"
        f"thresholds:\n"
        f"  staleness_days: 90\n"
        f"\n"
        f"discovery:\n"
        f"  exclude_dirs: []\n"
    )
    return config_path


def _ensure_gitignore(repo_path: Path) -> None:
    """Add .rkp/local/ to .gitignore if not already present."""
    gitignore = repo_path / ".gitignore"
    entry = ".rkp/local/"

    if gitignore.exists():
        content = gitignore.read_text()
        if entry in content:
            return
        # Append with a newline separator if needed.
        if content and not content.endswith("\n"):
            content += "\n"
        content += f"{entry}\n"
        gitignore.write_text(content)
    # If no .gitignore exists, don't create one — the repo might not be using git.


def init(
    ctx: typer.Context,
) -> None:
    """Initialize RKP: scan, extract, and present findings."""
    state: AppState = ctx.obj
    repo_path = state.repo_path
    rkp_dir = repo_path / ".rkp"
    config_path = rkp_dir / "config.yaml"

    try:
        # 1. Check if already initialized
        if config_path.exists():
            if state.json_output:
                print_json(
                    {
                        "status": "already_initialized",
                        "message": "RKP already initialized. Use rkp refresh to update.",
                        "config_path": str(config_path),
                    }
                )
            elif not state.quiet:
                print_info("RKP already initialized. Use rkp refresh to update.")
            raise typer.Exit(code=0)

        # 2. Detect repo shape
        supported_langs, unsupported_langs = detect_languages(
            repo_path,
            excluded_dirs=state.config.excluded_dirs,
        )
        git_backend = state.ensure_git()

        if not state.quiet and not state.json_output:
            if supported_langs:
                lang_msg = f"Detected {' + '.join(sorted(supported_langs))} repository"
                if unsupported_langs:
                    lang_msg += (
                        f" ({', '.join(sorted(unsupported_langs))} files found "
                        f"but not in launch support envelope)"
                    )
                console.print(lang_msg)
            elif unsupported_langs:
                console.print(
                    f"Detected {', '.join(sorted(unsupported_langs))} files "
                    f"(not in launch support envelope)"
                )
            else:
                print_error("No recognized source files found.")
                raise typer.Exit(code=3)

            if git_backend is None:
                console.print("[yellow]Not a git repository. Using filesystem-only mode.[/yellow]")

        # Check for empty repo with only unsupported languages
        if not supported_langs and not _has_config_files(repo_path):
            if state.json_output:
                print_json(
                    {
                        "status": "no_supported_sources",
                        "message": "No supported source files found.",
                        "unsupported_languages": sorted(unsupported_langs),
                    }
                )
            elif not state.quiet:
                print_error("No supported source files found.")
            raise typer.Exit(code=3)

        # 3. Create .rkp/ directory structure
        rkp_dir.mkdir(exist_ok=True)
        (rkp_dir / "local").mkdir(exist_ok=True)
        (rkp_dir / "overrides").mkdir(exist_ok=True)
        _ensure_gitignore(repo_path)

        # 4. Run extraction
        # Suppress structlog in JSON/quiet mode to keep stdout clean.
        if state.json_output or state.quiet:
            import logging

            logging.getLogger().setLevel(logging.CRITICAL)

        db = state.ensure_db()
        from rkp.graph.repo_graph import SqliteRepoGraph
        from rkp.indexer.orchestrator import run_extraction
        from rkp.store.claims import SqliteClaimStore

        claim_store = SqliteClaimStore(db)
        repo_id = str(repo_path)
        branch = git_backend.current_branch() if git_backend else "main"

        graph = SqliteRepoGraph(db)

        if not state.quiet and not state.json_output:
            print_info("Running extraction...")

        summary = run_extraction(
            repo_path,
            claim_store,
            repo_id=repo_id,
            branch=branch,
            git_backend=git_backend,
            graph=graph,
            config=state.config,
        )

        # 5. Save index metadata
        from rkp.store.metadata import IndexMetadata, SqliteMetadataStore

        metadata_store = SqliteMetadataStore(db)
        metadata_store.save(
            IndexMetadata(
                last_indexed=SqliteMetadataStore.now_iso(),
                repo_head=git_backend.head() if git_backend else "",
                branch=branch,
                file_count=summary.files_parsed,
                claim_count=summary.claims_created,
            )
        )

        # 6. Load overrides from .rkp/overrides/ (round-trip guarantee, AC-23).
        overrides_dir = rkp_dir / "overrides"
        if overrides_dir.exists() and any(overrides_dir.glob("*.yaml")):
            from rkp.store.overrides import FileSystemOverrideStore

            override_store = FileSystemOverrideStore(overrides_dir)
            apply_result = override_store.apply_overrides(claim_store, repo_id=repo_id)

            if not state.quiet and not state.json_output:
                if apply_result.applied:
                    action_parts = [f"{n} {a}" for a, n in apply_result.by_action]
                    console.print(
                        f"Applied {apply_result.applied} overrides from .rkp/overrides/ "
                        f"({', '.join(action_parts)})"
                    )
                if apply_result.skipped:
                    console.print(
                        f"[yellow]{apply_result.skipped} overrides skipped "
                        f"(claims not found — codebase may have changed)[/yellow]"
                    )

        # 6. Write config
        _write_default_config(rkp_dir, supported_langs)

        # 7. Present results
        claims = claim_store.list_claims(repo_id=repo_id)
        conflicts = [c for c in claims if c.claim_type == ClaimType.CONFLICT]
        needs_review = [c for c in claims if c.review_state == ReviewState.UNREVIEWED]
        needs_declaration = [c for c in claims if c.review_state == ReviewState.NEEDS_DECLARATION]

        if state.json_output:
            type_counts: Counter[str] = Counter()
            for claim in claims:
                type_counts[claim.claim_type.value] += 1

            print_json(
                {
                    "status": "success",
                    "files_parsed": summary.files_parsed,
                    "claims_created": summary.claims_created,
                    "claims_deduplicated": summary.claims_deduplicated,
                    "claim_counts": dict(type_counts),
                    "conflicts": len(conflicts),
                    "needs_review": len(needs_review),
                    "needs_declaration": len(needs_declaration),
                    "config_path": str(config_path),
                    "supported_languages": sorted(supported_langs),
                    "unsupported_languages": sorted(unsupported_langs),
                    "next_steps": [
                        "rkp preview --host codex",
                        "rkp preview --host claude",
                        "rkp status",
                        "rkp serve",
                    ],
                }
            )
        elif not state.quiet:
            console.print(
                f"\nExtracted {summary.claims_created} claims from "
                f"{summary.files_parsed} files"
                + (f" ({len(conflicts)} conflicts detected)" if conflicts else "")
            )
            console.print()

            # Summary table
            if claims:
                console.print(render_init_summary(claims))

            if unsupported_langs:
                console.print(
                    f"\n[dim]Note: {', '.join(sorted(unsupported_langs))} files detected "
                    f"but not analyzed (outside launch support envelope)[/dim]"
                )

            # Next steps
            console.print("\n[bold]Next steps:[/bold]")
            console.print("  rkp preview --host codex     Preview AGENTS.md projection")
            console.print("  rkp preview --host claude    Preview CLAUDE.md projection")
            console.print("  rkp status                   Check index health")
            console.print("  rkp serve                    Start MCP server for your agent")

        # Exit code: 1 if findings (conflicts or needs-declaration), 0 otherwise
        if conflicts or needs_declaration:
            raise typer.Exit(code=1)
        raise typer.Exit(code=0)

    except typer.Exit:
        raise
    except PermissionError as exc:
        print_error(f"Permission denied: {exc}")
        raise typer.Exit(code=2) from exc
    except KeyboardInterrupt:
        raise typer.Exit(code=130) from None
    except Exception as exc:
        print_error(f"Initialization failed: {exc}")
        if state.verbose > 0:
            console.print_exception()
        raise typer.Exit(code=2) from exc


def _has_config_files(repo_path: Path) -> bool:
    """Check if the repo has any recognizable config files."""
    candidates = (
        "pyproject.toml",
        "package.json",
        "Makefile",
        "Dockerfile",
        "docker-compose.yml",
        "docker-compose.yaml",
        "compose.yml",
        "compose.yaml",
    )
    return any((repo_path / name).is_file() for name in candidates)
