"""Tests for CLAUDE.md adapter."""

from __future__ import annotations

import json
import re
from dataclasses import replace

from rkp.core.claim_builder import ClaimBuilder
from rkp.core.types import ClaimType, RiskClass, Sensitivity, SourceAuthority
from rkp.projection.adapters.claude_md import ClaudeMdAdapter
from rkp.projection.budget import BudgetTracker
from rkp.projection.capability_matrix import CLAUDE_CODE_CAPABILITY
from rkp.projection.engine import ProjectionPolicy, project


class TestClaudeAdapterProjection:
    def test_basic_projection(self, builder: ClaimBuilder) -> None:
        """Known claims produce expected CLAUDE.md output."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=("pyproject.toml",),
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        assert "CLAUDE.md" in files
        content = files["CLAUDE.md"]
        assert "## Commands" in content
        assert "`pytest`" in content
        assert "Generated by RKP v0.1.0" in content

    def test_thin_claude_md(self, builder: ClaimBuilder) -> None:
        """CLAUDE.md with many claims stays under 200 lines."""
        claims = []
        for i in range(100):
            claim = builder.build(
                content=f"Convention rule {i} with some detailed description",
                claim_type=ClaimType.ALWAYS_ON_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.96,
                applicability=("all",),
            )
            claims.append(claim)

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, CLAUDE_CODE_CAPABILITY, policy)

        content = result.adapter_result.files["CLAUDE.md"]
        line_count = content.count("\n")
        assert line_count <= 200, f"CLAUDE.md is {line_count} lines, exceeds 200-line budget"

    def test_broad_applicability_in_claude_md(self, builder: ClaimBuilder) -> None:
        """Broad-applicability claims appear in CLAUDE.md."""
        claim = builder.build(
            content="Use snake_case for function names",
            claim_type=ClaimType.ALWAYS_ON_RULE,
            source_authority=SourceAuthority.INFERRED_HIGH,
            confidence=1.0,
            applicability=("all",),
        )

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project([claim], adapter, CLAUDE_CODE_CAPABILITY, policy)

        content = result.adapter_result.files["CLAUDE.md"]
        assert "snake_case" in content

    def test_narrow_applicability_in_skills(self, builder: ClaimBuilder) -> None:
        """Narrow-applicability claims → routed to skills, not CLAUDE.md."""
        claims = [
            builder.build(
                content="Run pytest with --cov flag",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.95,
                applicability=("testing",),
            ),
            builder.build(
                content="Use pytest-xdist for parallel testing",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.95,
                applicability=("testing",),
            ),
        ]

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        claude_md = files["CLAUDE.md"]

        # Should not be in CLAUDE.md body
        assert "pytest-xdist" not in claude_md or "Skills" in claude_md
        # Should be in skills
        skill_files = {k: v for k, v in files.items() if k.startswith(".claude/skills/")}
        assert len(skill_files) >= 1

    def test_path_scoped_claims_in_rules(self, builder: ClaimBuilder) -> None:
        """Path-scoped claims → .claude/rules/ files with paths frontmatter."""
        claim = builder.build(
            content="Payment module requires audit logging",
            claim_type=ClaimType.SCOPED_RULE,
            source_authority=SourceAuthority.INFERRED_HIGH,
            scope="src/payments/**",
            confidence=0.95,
            applicability=("security",),
        )

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project([claim], adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        rule_files = {k: v for k, v in files.items() if k.startswith(".claude/rules/")}
        assert len(rule_files) >= 1

        for content in rule_files.values():
            assert "---" in content
            assert "paths:" in content
            assert "src/payments/**" in content
            assert "Payment module" in content

    def test_destructive_guardrail_in_settings(self, builder: ClaimBuilder) -> None:
        """Destructive command guardrail → settings.json deny entry."""
        claim = builder.build(
            content="Command `rm -rf dist/` is classified as destructive "
            "— require explicit confirmation before running",
            claim_type=ClaimType.PERMISSION_RESTRICTION,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            confidence=1.0,
            applicability=("destructive", "security"),
        )

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project([claim], adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        assert ".claude/settings-snippet.json" in files
        settings = json.loads(files[".claude/settings-snippet.json"])
        assert "permissions" in settings
        assert "deny" in settings["permissions"]
        deny = settings["permissions"]["deny"]
        assert any("Bash(rm -rf dist/*)" in d for d in deny)

    def test_non_destructive_guardrail_advisory_only(self, builder: ClaimBuilder) -> None:
        """Non-destructive guardrail → advisory text in CLAUDE.md, NOT settings.json."""
        claim = builder.build(
            content="CI runs security scan: `npm audit` — ensure changes pass",
            claim_type=ClaimType.PERMISSION_RESTRICTION,
            source_authority=SourceAuthority.CI_OBSERVED,
            confidence=0.9,
            applicability=("security",),
        )

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project([claim], adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        # Should be in CLAUDE.md as advisory
        assert "npm audit" in files["CLAUDE.md"]
        # Should NOT generate settings snippet (confidence < 0.95 or not destructive)
        assert ".claude/settings-snippet.json" not in files

    def test_multiple_guardrails_combined_settings(self, builder: ClaimBuilder) -> None:
        """Multiple enforceable guardrails → combined settings snippet."""
        claims = [
            builder.build(
                content="Command `db:reset` is classified as destructive "
                "— require explicit confirmation before running",
                claim_type=ClaimType.PERMISSION_RESTRICTION,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                applicability=("destructive", "security"),
            ),
            builder.build(
                content="Command `deploy:prod` is classified as destructive "
                "— require explicit confirmation before running",
                claim_type=ClaimType.PERMISSION_RESTRICTION,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                applicability=("destructive", "security"),
            ),
        ]

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        assert ".claude/settings-snippet.json" in files
        settings = json.loads(files[".claude/settings-snippet.json"])
        deny = settings["permissions"]["deny"]
        assert len(deny) == 2

    def test_sensitivity_filtering(self, builder: ClaimBuilder) -> None:
        """Local-only claims excluded from all outputs."""
        public = builder.build(
            content="pytest",
            claim_type=ClaimType.VALIDATED_COMMAND,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            sensitivity=Sensitivity.PUBLIC,
            confidence=1.0,
        )
        local = builder.build(
            content="secret-internal-cmd",
            claim_type=ClaimType.VALIDATED_COMMAND,
            source_authority=SourceAuthority.EXECUTABLE_CONFIG,
            sensitivity=Sensitivity.LOCAL_ONLY,
            confidence=1.0,
        )
        public = replace(public, risk_class=RiskClass.TEST_EXECUTION)
        local = replace(local, risk_class=RiskClass.BUILD)

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project([public, local], adapter, CLAUDE_CODE_CAPABILITY, policy)

        # Check all files for leakage
        for content in result.adapter_result.files.values():
            assert "secret-internal-cmd" not in content
        assert len(result.excluded_sensitive) == 1

    def test_deterministic_output(self, builder: ClaimBuilder) -> None:
        """Same claims → byte-identical CLAUDE.md, rules, skills, settings."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
            ),
            builder.build(
                content="Use snake_case",
                claim_type=ClaimType.ALWAYS_ON_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=1.0,
                applicability=("all",),
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = ClaudeMdAdapter()

        budget1 = BudgetTracker(soft_budget_lines=200)
        result1 = adapter.project(claims, CLAUDE_CODE_CAPABILITY, budget1)

        budget2 = BudgetTracker(soft_budget_lines=200)
        result2 = adapter.project(claims, CLAUDE_CODE_CAPABILITY, budget2)

        # Normalize timestamps
        for key in result1.files:
            content1 = re.sub(r"timestamp: [^\s|]+", "timestamp: X", result1.files[key])
            content2 = re.sub(r"timestamp: [^\s|]+", "timestamp: X", result2.files[key])
            assert content1 == content2, f"Non-deterministic output for {key}"

    def test_empty_claims(self, builder: ClaimBuilder) -> None:
        """Empty claims produce minimal CLAUDE.md."""
        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project([], adapter, CLAUDE_CODE_CAPABILITY, policy)

        assert "CLAUDE.md" in result.adapter_result.files
        assert "Generated by RKP" in result.adapter_result.files["CLAUDE.md"]

    def test_skills_reference_in_claude_md(self, builder: ClaimBuilder) -> None:
        """When skills are generated, CLAUDE.md includes reference list."""
        claims = [
            builder.build(
                content="Run pytest for tests",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.95,
                applicability=("testing",),
            ),
            builder.build(
                content="Use pytest-cov for coverage",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.95,
                applicability=("testing",),
            ),
        ]

        adapter = ClaudeMdAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, CLAUDE_CODE_CAPABILITY, policy)

        files = result.adapter_result.files
        claude_md = files["CLAUDE.md"]
        # Should have a Skills section referencing the generated skill
        skill_files = [k for k in files if k.startswith(".claude/skills/")]
        if skill_files:
            assert "## Skills" in claude_md
