"""Tests for Copilot adapter."""

from __future__ import annotations

import json
from dataclasses import replace

from rkp.core.claim_builder import ClaimBuilder
from rkp.core.types import ClaimType, RiskClass, Sensitivity, SourceAuthority
from rkp.projection.adapters.copilot import CopilotAdapter
from rkp.projection.capability_matrix import COPILOT_CAPABILITY
from rkp.projection.engine import ProjectionPolicy, project


class TestCopilotAdapterProjection:
    def test_basic_projection(self, builder: ClaimBuilder) -> None:
        """Known claims produce expected copilot-instructions.md output."""
        claims = [
            builder.build(
                content="pytest",
                claim_type=ClaimType.VALIDATED_COMMAND,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=("pyproject.toml",),
            ),
        ]
        claims[0] = replace(claims[0], risk_class=RiskClass.TEST_EXECUTION)

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        files = result.adapter_result.files
        assert ".github/copilot-instructions.md" in files
        content = files[".github/copilot-instructions.md"]
        assert "Generated by RKP v0.1.0" in content
        assert "`pytest`" in content

    def test_produces_all_artifact_types(self, builder: ClaimBuilder) -> None:
        """Copilot adapter produces all 4 artifact types."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                    evidence=("pyproject.toml",),
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
            builder.build(
                content="Python 3.12",
                claim_type=ClaimType.ENVIRONMENT_PREREQUISITE,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                evidence=(".python-version",),
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        files = result.adapter_result.files
        assert ".github/copilot-instructions.md" in files
        assert ".github/workflows/copilot-setup-steps.yml" in files
        assert ".copilot-tool-allowlist.json" in files

    def test_thin_copilot_instructions(self, builder: ClaimBuilder) -> None:
        """copilot-instructions.md should be thin — not a copy of AGENTS.md."""
        # Create many convention claims
        claims = [
            builder.build(
                content=f"Convention rule {i} with detailed description",
                claim_type=ClaimType.ALWAYS_ON_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                confidence=0.96,
                applicability=("all",),
            )
            for i in range(50)
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        content = result.adapter_result.files[".github/copilot-instructions.md"]
        # Only top 10 conventions should be included
        line_count = content.count("\n")
        assert line_count <= 100, f"copilot-instructions.md is {line_count} lines — should be thin"

    def test_scoped_claims_to_instructions_md(self, builder: ClaimBuilder) -> None:
        """Scoped claims produce .instructions.md files with applyTo frontmatter."""
        claims = [
            builder.build(
                content="Use strict TypeScript in this module",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                scope="src/payments/**",
                confidence=0.95,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        files = result.adapter_result.files
        instruction_files = {
            k: v for k, v in files.items() if k.startswith(".github/instructions/")
        }
        assert len(instruction_files) >= 1

        # Check applyTo frontmatter
        for content in instruction_files.values():
            assert "applyTo:" in content
            assert "---" in content

    def test_scope_grouping(self, builder: ClaimBuilder) -> None:
        """Overlapping scopes are consolidated into fewer files."""
        claims = [
            builder.build(
                content="Rule A for payments",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                scope="src/payments/**",
                confidence=0.95,
            ),
            builder.build(
                content="Rule B for payments",
                claim_type=ClaimType.SCOPED_RULE,
                source_authority=SourceAuthority.INFERRED_HIGH,
                scope="src/payments/**",
                confidence=0.95,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        instruction_files = {
            k: v
            for k, v in result.adapter_result.files.items()
            if k.startswith(".github/instructions/")
        }
        # Both claims should be in the same file
        assert len(instruction_files) == 1

    def test_determinism(self, builder: ClaimBuilder) -> None:
        """Same claims produce identical output."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()

        result1 = project(claims, adapter, COPILOT_CAPABILITY, policy)
        result2 = project(claims, adapter, COPILOT_CAPABILITY, policy)

        # Strip timestamps for comparison
        files1 = result1.adapter_result.files
        files2 = result2.adapter_result.files
        assert set(files1.keys()) == set(files2.keys())

    def test_sensitivity_filtering(self, builder: ClaimBuilder) -> None:
        """local-only claims are excluded from all Copilot outputs."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
            replace(
                builder.build(
                    content="Secret local command",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                sensitivity=Sensitivity.LOCAL_ONLY,
                risk_class=RiskClass.TEST_EXECUTION,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        # Local-only should be excluded
        assert len(result.excluded_sensitive) == 1
        # And not in any file content
        for content in result.adapter_result.files.values():
            assert "Secret local command" not in content

    def test_guardrails_prominent(self, builder: ClaimBuilder) -> None:
        """Destructive command warnings are prominent in copilot-instructions.md."""
        claims = [
            builder.build(
                content="Command `db:reset` is classified as destructive "
                "— require explicit confirmation before running",
                claim_type=ClaimType.PERMISSION_RESTRICTION,
                source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                confidence=1.0,
                applicability=("destructive", "security"),
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        content = result.adapter_result.files[".github/copilot-instructions.md"]
        assert "## Restrictions" in content
        assert "WARNING" in content
        assert "db:reset" in content
        # Restrictions should appear before other sections
        restrictions_pos = content.find("## Restrictions")
        commands_pos = content.find("## Key Commands")
        if commands_pos >= 0:
            assert restrictions_pos < commands_pos

    def test_tool_allowlist_in_output(self, builder: ClaimBuilder) -> None:
        """Tool allowlist is valid JSON with correct structure."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        allowlist_json = result.adapter_result.files[".copilot-tool-allowlist.json"]
        allowlist = json.loads(allowlist_json)
        assert "tools" in allowlist
        assert "repo-knowledge-plane" in allowlist["tools"]
        assert "allow" in allowlist["tools"]["repo-knowledge-plane"]
        assert "deny" in allowlist["tools"]["repo-knowledge-plane"]

    def test_overflow_report_has_decisions(self, builder: ClaimBuilder) -> None:
        """Overflow report includes projection decisions."""
        claims = [
            replace(
                builder.build(
                    content="pytest",
                    claim_type=ClaimType.VALIDATED_COMMAND,
                    source_authority=SourceAuthority.EXECUTABLE_CONFIG,
                    confidence=1.0,
                ),
                risk_class=RiskClass.TEST_EXECUTION,
            ),
        ]

        adapter = CopilotAdapter()
        policy = ProjectionPolicy()
        result = project(claims, adapter, COPILOT_CAPABILITY, policy)

        overflow = result.adapter_result.overflow_report
        assert "decisions" in overflow
        assert "setup_steps_validation" in overflow
