"""Export conformance — automated round-trip validation per adapter."""

from __future__ import annotations

import sqlite3

import structlog
import yaml

from rkp.core.models import Claim
from rkp.core.types import ClaimType, Sensitivity, SourceAuthority
from rkp.projection.adapters.agents_md import AgentsMdAdapter
from rkp.projection.adapters.base import AdapterResult
from rkp.projection.adapters.claude_md import ClaudeMdAdapter
from rkp.projection.adapters.copilot import CopilotAdapter, validate_setup_steps
from rkp.projection.capability_matrix import (
    AGENTS_MD_CAPABILITY,
    CLAUDE_CODE_CAPABILITY,
    COPILOT_CAPABILITY,
    HostCapability,
)
from rkp.projection.engine import ProjectionPolicy, project
from rkp.projection.sensitivity import filter_sensitive
from rkp.quality.types import ConformanceResult
from rkp.store.claims import SqliteClaimStore

logger = structlog.get_logger()

# High-authority sources whose claims should appear in always-on content.
_HIGH_AUTHORITY = frozenset(
    {
        SourceAuthority.HUMAN_OVERRIDE,
        SourceAuthority.DECLARED_REVIEWED,
        SourceAuthority.EXECUTABLE_CONFIG,
        SourceAuthority.CI_OBSERVED,
        SourceAuthority.INFERRED_HIGH,
    }
)


def _get_adapter_and_capability(
    adapter_name: str,
) -> tuple[AgentsMdAdapter | ClaudeMdAdapter | CopilotAdapter, HostCapability]:
    """Get the adapter instance and capability for a given name."""
    if adapter_name == "agents-md":
        return AgentsMdAdapter(), AGENTS_MD_CAPABILITY
    elif adapter_name == "claude":
        return ClaudeMdAdapter(), CLAUDE_CODE_CAPABILITY
    elif adapter_name == "copilot":
        return CopilotAdapter(), COPILOT_CAPABILITY
    else:
        msg = f"Unknown adapter: {adapter_name}"
        raise ValueError(msg)


def _validate_format(adapter_name: str, result: AdapterResult) -> tuple[bool, list[str]]:
    """Validate that output is syntactically valid for the host."""
    errors: list[str] = []

    if adapter_name == "agents-md":
        content = result.files.get("AGENTS.md", "")
        if not content.strip():
            errors.append("AGENTS.md is empty")
        # Markdown validity: check for header
        if "<!-- Generated by RKP" not in content:
            errors.append("Missing generation header")

    elif adapter_name == "claude":
        content = result.files.get("CLAUDE.md", "")
        if not content.strip():
            errors.append("CLAUDE.md is empty")
        if "<!-- Generated by RKP" not in content:
            errors.append("Missing generation header")
        # Check settings snippet is valid JSON if present
        settings = result.files.get(".claude/settings-snippet.json")
        if settings is not None:
            import json

            try:
                json.loads(settings)
            except json.JSONDecodeError as e:
                errors.append(f"Invalid settings-snippet.json: {e}")

    elif adapter_name == "copilot":
        instructions = result.files.get(".github/copilot-instructions.md", "")
        if not instructions.strip():
            errors.append("copilot-instructions.md is empty")

        setup_steps = result.files.get(".github/workflows/copilot-setup-steps.yml")
        if setup_steps is not None:
            try:
                parsed = yaml.safe_load(setup_steps)
                if isinstance(parsed, dict):
                    from typing import Any, cast

                    validation_errors = validate_setup_steps(cast(dict[str, Any], parsed))
                    errors.extend(validation_errors)
            except yaml.YAMLError as e:
                errors.append(f"Invalid YAML in setup-steps: {e}")

        allowlist = result.files.get(".copilot-tool-allowlist.json")
        if allowlist is not None:
            import json

            try:
                json.loads(allowlist)
            except json.JSONDecodeError as e:
                errors.append(f"Invalid tool-allowlist.json: {e}")

    return len(errors) == 0, errors


def _check_budget(adapter_name: str, result: AdapterResult) -> bool:
    """Check if output is within budget constraints."""
    if adapter_name == "agents-md":
        content = result.files.get("AGENTS.md", "")
        return len(content.encode("utf-8")) <= 32 * 1024
    elif adapter_name == "claude":
        content = result.files.get("CLAUDE.md", "")
        return content.count("\n") <= 250  # soft budget 200 + margin
    elif adapter_name == "copilot":
        content = result.files.get(".github/copilot-instructions.md", "")
        return content.count("\n") <= 350  # soft budget 300 + margin
    return True


def _check_claims_inclusion(
    claims: list[Claim],
    result: AdapterResult,
    adapter_name: str,
) -> tuple[int, int, int, int]:
    """Check which claims are correctly included/excluded.

    Returns (included_correctly, excluded_correctly,
             incorrectly_included, incorrectly_excluded).
    """
    # Concatenate all file contents to check claim presence
    all_content = "\n".join(result.files.values()).lower()

    should_include: list[Claim] = []
    should_exclude: list[Claim] = []

    for claim in claims:
        # Local-only and team-only should be excluded from public projections
        if claim.sensitivity in (Sensitivity.LOCAL_ONLY, Sensitivity.TEAM_ONLY):
            should_exclude.append(claim)
            continue
        # Suppressed/tombstoned claims should be excluded
        if claim.review_state.value in ("suppressed", "tombstoned"):
            should_exclude.append(claim)
            continue
        # High-authority, projectable claim types should be included
        if (
            claim.claim_type
            in (
                ClaimType.VALIDATED_COMMAND,
                ClaimType.ALWAYS_ON_RULE,
                ClaimType.PERMISSION_RESTRICTION,
            )
            and claim.source_authority in _HIGH_AUTHORITY
        ) or (
            claim.claim_type == ClaimType.SCOPED_RULE and claim.source_authority in _HIGH_AUTHORITY
        ):
            should_include.append(claim)

    included_correctly = 0
    incorrectly_excluded = 0
    for claim in should_include:
        # Check if claim content appears in output (case-insensitive substring)
        if claim.content.lower() in all_content:
            included_correctly += 1
        else:
            incorrectly_excluded += 1

    excluded_correctly = 0
    incorrectly_included = 0
    for claim in should_exclude:
        if claim.content.lower() in all_content:
            incorrectly_included += 1
        else:
            excluded_correctly += 1

    return included_correctly, excluded_correctly, incorrectly_included, incorrectly_excluded


def evaluate_conformance(
    db: sqlite3.Connection,
    adapter_name: str,
    *,
    repo_id: str = "",
) -> ConformanceResult:
    """Evaluate export conformance for a single adapter.

    1. Load claims from the store
    2. Project through the adapter
    3. Validate format, budget, determinism, claim inclusion/exclusion
    4. Compute conformance score
    """
    store = SqliteClaimStore(db)
    claims = store.list_claims(repo_id=repo_id if repo_id else None)

    if not claims:
        return ConformanceResult(
            adapter_name=adapter_name,
            valid_format=True,
            claims_included_correctly=0,
            claims_excluded_correctly=0,
            claims_incorrectly_included=0,
            claims_incorrectly_excluded=0,
            within_budget=True,
            deterministic=True,
            score=1.0,
            details=("No claims to project",),
        )

    adapter, capability = _get_adapter_and_capability(adapter_name)
    policy = ProjectionPolicy()

    # First projection
    result1 = project(claims, adapter, capability, policy)

    # Second projection for determinism check
    result2 = project(claims, adapter, capability, policy)

    deterministic = result1.adapter_result.files == result2.adapter_result.files

    # Format validation
    valid_format, format_errors = _validate_format(adapter_name, result1.adapter_result)

    # Budget check
    within_budget = _check_budget(adapter_name, result1.adapter_result)

    # Claims inclusion check - use the public-filtered claims
    _public_claims, _ = filter_sensitive(claims, Sensitivity.PUBLIC)
    incl_ok, excl_ok, incl_bad, excl_bad = _check_claims_inclusion(
        claims, result1.adapter_result, adapter_name
    )

    # Score calculation: weighted average
    total_checks = max(incl_ok + excl_ok + incl_bad + excl_bad, 1)
    correct_checks = incl_ok + excl_ok
    inclusion_score = correct_checks / total_checks

    # Overall score
    format_score = 1.0 if valid_format else 0.0
    budget_score = 1.0 if within_budget else 0.0
    determinism_score = 1.0 if deterministic else 0.0

    # Weighted: inclusion 60%, format 15%, budget 15%, determinism 10%
    score = (
        inclusion_score * 0.60
        + format_score * 0.15
        + budget_score * 0.15
        + determinism_score * 0.10
    )

    details_list: list[str] = []
    if format_errors:
        details_list.extend(f"format: {e}" for e in format_errors)
    if not within_budget:
        details_list.append("output exceeds budget")
    if not deterministic:
        details_list.append("non-deterministic output")

    return ConformanceResult(
        adapter_name=adapter_name,
        valid_format=valid_format,
        claims_included_correctly=incl_ok,
        claims_excluded_correctly=excl_ok,
        claims_incorrectly_included=incl_bad,
        claims_incorrectly_excluded=excl_bad,
        within_budget=within_budget,
        deterministic=deterministic,
        score=round(score, 4),
        details=tuple(details_list),
    )
